### PR TITLE
cmake, ci: Consistently put all `CPPFLAGS` into `-DAPPEND_CPPFLAGS`

### PR DESCRIPTION
**Pull request by hebasto**
This PR addresses this https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1680665264:
> CPP flag handling seems inconsistent throughout the CI changes, which is confusing. It'd be good to consistently put all CPPFLAGS into CPPFLAGS, rather than having them sometimes in CXXFLAGS, sometimes in (append) CPPFLAGS, and sometimes spread between the two, i.e here.

The CI logs are available here: https://cirrus-ci.com/build/5765939633848320

### CODE REVIEW

**Comment by hebasto** [comment]
cc @fanquake

**Review by TheCharlatan — APPROVED** [review]
lgtm

Nit: I'd find it a bit more readable if each of the variables were on their own line.

**Comment by hebasto** [comment]
@TheCharlatan 
> lgtm
> 
> Nit: I'd find it a bit more readable if each of the variables were on their own line.

Updated per your nit. Does it look better now?

**Comment by hebasto** [comment]
The CI logs for the recent changes are available here: https://cirrus-ci.com/build/5863226292830208.

**Review by TheCharlatan — APPROVED** [review]
lgtm

**Pull request merged**
