### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/commit/700eaae6809d375692b71b0aed5be9f44c6c1cad) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/c1223188e0a5fb11c3a1b9224511a49dc2f848ed) one with the squashed "!fixup" and "FIXUP:" commits.

Steps to reproduce:
1. Run the command as follows:
```
git checkout 700eaae6809d375692b71b0aed5be9f44c6c1cad
git rebase -i --autosquash c1223188e0a5fb11c3a1b9224511a49dc2f848ed
```
There are a few conflicts that have to be resolved.

At this point the diff between `HEAD` and this PR branch must coincides with changes in the following item 4.

2. Manually move changes from "FIXUP:" commits to the appropriate previous ones.

3. Reorder the recent commits to pop up the CI one.

4. Backport changes from:
- https://github.com/bitcoin/bitcoin/pull/28955
- https://github.com/bitcoin/bitcoin/pull/29458

---

Changes from https://github.com/bitcoin/bitcoin/pull/27375 are to be backported in the dedicated PR shortly after approving this one.

---

~If it happens that https://github.com/hebasto/bitcoin/pull/82 will be approved first (fingers crossed :crossed_fingers:), I'll be happy to update this PR accordingly.~ Incorporated :)

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @m3dwards @TheCharlatan @pablomartin4btc @vasild  :)

**Review by pablomartin4btc — COMMENTED** [review]
ACK d542bbadec3107977e5930aac63c8d8cad843941

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
1d0d750a85500137e5f6b8e85100fd02db19da9186394f80c20c81228110c275  guix-build-d542bbadec31/output/aarch64-linux-gnu/SHA256SUMS.part
a8f27449432aabfacd74fd5848fa323aa40e2d51505223998b29d62defb05d8f  guix-build-d542bbadec31/output/aarch64-linux-gnu/bitcoin-d542bbadec31-aarch64-linux-gnu-debug.tar.gz
eadaaea31e46263c84d25b0a843fbdffdf2b565c6e0d22af37743857954fa128  guix-build-d542bbadec31/output/aarch64-linux-gnu/bitcoin-d542bbadec31-aarch64-linux-gnu.tar.gz
1146b32fc51d1253b30cebb7485d2d6b38746d8984a8296ef5bec1a130a74865  guix-build-d542bbadec31/output/arm-linux-gnueabihf/SHA256SUMS.part
7c4101cea5901419f71f9269a4f15dd0b034c7fbcc223429eb92f31aaf6e9921  guix-build-d542bbadec31/output/arm-linux-gnueabihf/bitcoin-d542bbadec31-arm-linux-gnueabihf-debug.tar.gz
f815ca679482e9a73bbc3adde8695ef21317fec86c1aeafcde952156d19608de  guix-build-d542bbadec31/output/arm-linux-gnueabihf/bitcoin-d542bbadec31-arm-linux-gnueabihf.tar.gz
0a58fb7a3bcd1dc474635bae68f6fcde066e42f01ff56f58a87ce31364e204e7  guix-build-d542bbadec31/output/dist-archive/bitcoin-d542bbadec31.tar.gz
49521248a2b610a6451c8252545a2e97d27cc0522d528026299df23efd976ea6  guix-build-d542bbadec31/output/powerpc64-linux-gnu/SHA256SUMS.part
a7c59331b0df5a522fb443042649d90900bfb69618606c10fe0932cee2ecb048  guix-build-d542bbadec31/output/powerpc64-linux-gnu/bitcoin-d542bbadec31-powerpc64-linux-gnu-debug.tar.gz
c5d62a229c2099321f94154235d592e156a07039e52014f327140deb0ff26b0a  guix-build-d542bbadec31/output/powerpc64-linux-gnu/bitcoin-d542bbadec31-powerpc64-linux-gnu.tar.gz
f478740fbe48a4a50bbe7a5b6fcebbc7c1d550204f27c6dc518e63b974fa3f0b  guix-build-d542bbadec31/output/riscv64-linux-gnu/SHA256SUMS.part
ff73061551ee69a22e58807a231f9fad28f47e0f04b379091b066965300acc6f  guix-build-d542bbadec31/output/riscv64-linux-gnu/bitcoin-d542bbadec31-riscv64-linux-gnu-debug.tar.gz
833a64ae0faecde21834f9c1dec92641e2e13e840acc50dad74ce107d0c2b83f  guix-build-d542bbadec31/output/riscv64-linux-gnu/bitcoin-d542bbadec31-riscv64-linux-gnu.tar.gz
4c86996445c125dae00fd5ed5408f7dfa44d72559e7c7ef35f872fc5c3cff7e3  guix-build-d542bbadec31/output/x86_64-linux-gnu/SHA256SUMS.part
912a3ad3bfcd492984d2f73731a3903f8adfdc98497ce783aebacf544d0d1b01  guix-build-d542bbadec31/output/x86_64-linux-gnu/bitcoin-d542bbadec31-x86_64-linux-gnu-debug.tar.gz
96ae39fa19d8980c035262a3308a54a1d7aec049c614dc94c376e076416c0812  guix-build-d542bbadec31/output/x86_64-linux-gnu/bitcoin-d542bbadec31-x86_64-linux-gnu.tar.gz
fdc7c303c9b00a1f895cb40e1d9abfd7890a6376fff05d3ea956b5ba61ae8c2a  guix-build-d542bbadec31/output/x86_64-w64-mingw32/SHA256SUMS.part
13c5cf8ca5f0237b0367e13c89708aab783e4ba78bb51b9db508756b00f21c17  guix-build-d542bbadec31/output/x86_64-w64-mingw32/bitcoin-d542bbadec31-win64-debug.zip
6e480220917afe5b75628e7e7ea8e33a7ec47cb0c2ffdee5263bf1e36f2afe19  guix-build-d542bbadec31/output/x86_64-w64-mingw32/bitcoin-d542bbadec31-win64-setup-unsigned.exe
81bcfe54f7488be2442913da4832d7661e25340858345925a03f4b00ea2e7ada  guix-build-d542bbadec31/output/x86_64-w64-mingw32/bitcoin-d542bbadec31-win64-unsigned.tar.gz
acc5b700a8ceb18174b847446e997f2be4e1e4a5e67b3c178f8ed5d14cd9c44e  guix-build-d542bbadec31/output/x86_64-w64-mingw32/bitcoin-d542bbadec31-win64.zip
```

**Comment by hebasto** [comment]
> If it happens that #82 will be approved first (fingers crossed 🤞), I'll be happy to update this PR accordingly.

I've incorporated the recent merged PRs:
- https://github.com/hebasto/bitcoin/pull/82
- https://github.com/hebasto/bitcoin/pull/128

Ready for the final review :)

**Comment by TheCharlatan** [comment]
lgtm,
Guix builds:
```
4730daf1d2542bdbd8b1565bd18cd5b2ae696324527a09e79fd642447eecb141  guix-build-80784278b5f2/output/aarch64-linux-gnu/SHA256SUMS.part
4819630c8b818efeffb6fd5121dafc7d8a4fb28127cb1d82816a2ae1d2af2ce3  guix-build-80784278b5f2/output/aarch64-linux-gnu/bitcoin-80784278b5f2-aarch64-linux-gnu-debug.tar.gz
42ddb743870a748ec365298b4545f0a18eb3756cbad68bcba8aa53b153f26433  guix-build-80784278b5f2/output/aarch64-linux-gnu/bitcoin-80784278b5f2-aarch64-linux-gnu.tar.gz
72d89c5f4db5a3f4bb3eaf544a5b4972d2be9f6ce88e9c4583f0a17718333a3a  guix-build-80784278b5f2/output/arm-linux-gnueabihf/SHA256SUMS.part
66185cfb07be4516d9833422c0960dfe084485599ce492fcc214270f448c051c  guix-build-80784278b5f2/output/arm-linux-gnueabihf/bitcoin-80784278b5f2-arm-linux-gnueabihf-debug.tar.gz
e4f74ba9b0002e6389e030f52c3bb1f9ff37384d95b404dacec5c650918473ad  guix-build-80784278b5f2/output/arm-linux-gnueabihf/bitcoin-80784278b5f2-arm-linux-gnueabihf.tar.gz
811294dae242cd4351fe1f279857d18433c89638f29b231262b8ed73c658c183  guix-build-80784278b5f2/output/dist-archive/bitcoin-80784278b5f2.tar.gz
223a2e9eedd1de05faeb583268f7e40380bf05344d38a12e81c79863b8de6061  guix-build-80784278b5f2/output/powerpc64-linux-gnu/SHA256SUMS.part
8dec299bf9bf0b909932b3739a36c4a8092885b76e551aab51a37ed6ace15f4a  guix-build-80784278b5f2/output/powerpc64-linux-gnu/bitcoin-80784278b5f2-powerpc64-linux-gnu-debug.tar.gz
ff7facb46d7b0c842b24fa72014316c5a8249b98f9ceba8ce9fe9bf5148016ed  guix-build-80784278b5f2/output/powerpc64-linux-gnu/bitcoin-80784278b5f2-powerpc64-linux-gnu.tar.gz
7c07fa51b35c416275f42ac5bfbe0b085808041696ee4b1aa6057699b76d4e9b  guix-build-80784278b5f2/output/riscv64-linux-gnu/SHA256SUMS.part
33e3406a4502fcf7093d896a09105fd1d4f7db438abc3a882648d0635ab64ce6  guix-build-80784278b5f2/output/riscv64-linux-gnu/bitcoin-80784278b5f2-riscv64-linux-gnu-debug.tar.gz
ccdc60b4a700afa8f844089d5592eb8fc3ea439985658ab3c6b029dd44161ad8  guix-build-80784278b5f2/output/riscv64-linux-gnu/bitcoin-80784278b5f2-riscv64-linux-gnu.tar.gz
ca4090d1d933e5587c4689b2d30524996901122de7e7783fb19b00305efdfa6e  guix-build-80784278b5f2/output/x86_64-linux-gnu/SHA256SUMS.part
0e8bd693506854f90354a17253b3b8dc3b2bf2f9a8c46584e15aa4295e227b1a  guix-build-80784278b5f2/output/x86_64-linux-gnu/bitcoin-80784278b5f2-x86_64-linux-gnu-debug.tar.gz
2b2eea974bd1ff3a705f991880bef175c9cfc0a6d5a465295980e3960f209058  guix-build-80784278b5f2/output/x86_64-linux-gnu/bitcoin-80784278b5f2-x86_64-linux-gnu.tar.gz
b975b0370b67a0ad93f906406f99dd5b2c12b35e28d4d6bac8aae19f3f02771e  guix-build-80784278b5f2/output/x86_64-w64-mingw32/SHA256SUMS.part
da6d623387a379e55a04282a4b021cbba58da3284af466652fd6d3f292a6cb03  guix-build-80784278b5f2/output/x86_64-w64-mingw32/bitcoin-80784278b5f2-win64-debug.zip
9bd6824c6fd6ec67a7622d25455f2582dd1b2ab920596eb5c67976c6f05dbf07  guix-build-80784278b5f2/output/x86_64-w64-mingw32/bitcoin-80784278b5f2-win64-setup-unsigned.exe
a5aeaec518f19b1a9768954066dfa09601187b852db92c4f073933fe1b8bcb62  guix-build-80784278b5f2/output/x86_64-w64-mingw32/bitcoin-80784278b5f2-win64-unsigned.tar.gz
c7437a26f8f8bacddc09c1c2b99fbc93e5ea4d1e0f8c71ec8d6479502636aaab  guix-build-80784278b5f2/output/x86_64-w64-mingw32/bitcoin-80784278b5f2-win64.zip
```

**Review by TheCharlatan — APPROVED** [review]

**Comment by hebasto** [comment]
@TheCharlatan  

Thank you for your review!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Comment by hebasto** [comment]
> Changes from [bitcoin#27375](https://github.com/bitcoin/bitcoin/pull/27375) are to be backported in the dedicated PR shortly after approving this one.

Done in https://github.com/hebasto/bitcoin/pull/132.

**Pull request closed without merging**
