### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/commit/1d7605615e3e30b842b56740083dfc13716bbd41) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/ecd23656db174adef61d3bd753d02698c3528192) one, which includes the main build system changes, with the squashed "!fixup" commits.

Steps to reproduce:
1. Run the command as follows:
```
git checkout 1d7605615e3e30b842b56740083dfc13716bbd41
git rebase -i --autosquash ecd23656db174adef61d3bd753d02698c3528192
```
There are a few conflicts that have to be resolved.

2. Squash the "FIXUP" commits manually (it must be a zero-diff change).

3. Reorder the recent commits to pop up the docs and CI changes (it must be a zero-diff change).

4. Port build system changes from:
- https://github.com/bitcoin/bitcoin/pull/29252
- https://github.com/bitcoin/bitcoin/pull/29739
- https://github.com/bitcoin/bitcoin/pull/30083

### CODE REVIEW

**Comment by hebasto** [comment]
For the master branch CI, please refer to https://github.com/bitcoin/bitcoin/pull/29790#issuecomment-2121349899:
- https://cirrus-ci.com/build/5261265398923264

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
628ce0b4e73c8024a3b74fb17c83b20e54ebcc8079c49aead6f84de7cae6caa8  guix-build-e8e0e69c7d54/output/aarch64-linux-gnu/SHA256SUMS.part
47fdae9eab52cdfac83c2c18bb712521f24fdbd66caae5741f0bf4d0ef590c3b  guix-build-e8e0e69c7d54/output/aarch64-linux-gnu/bitcoin-e8e0e69c7d54-aarch64-linux-gnu-debug.tar.gz
4af831aeea939c0c006a84ca541c342dee6a7ad0141a68a092d800ec56307463  guix-build-e8e0e69c7d54/output/aarch64-linux-gnu/bitcoin-e8e0e69c7d54-aarch64-linux-gnu.tar.gz
c6bde599fa9e2376476222a41f74f19c96289e872bce24b4847adcd93055fe5e  guix-build-e8e0e69c7d54/output/arm-linux-gnueabihf/SHA256SUMS.part
fbb1d008f7890d9f8e31735af372904aa47706ad967e8ec4ff3ccebe706a6dc9  guix-build-e8e0e69c7d54/output/arm-linux-gnueabihf/bitcoin-e8e0e69c7d54-arm-linux-gnueabihf-debug.tar.gz
b363b970a9c9a7683fcda6f427c0f2c08fdd26c57cf1af859632a39091e8cd54  guix-build-e8e0e69c7d54/output/arm-linux-gnueabihf/bitcoin-e8e0e69c7d54-arm-linux-gnueabihf.tar.gz
4c2658d8a66dba960bc3f372a64b792fd37a1e9b3f98e1e10c7b05f324e7d9c5  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/SHA256SUMS.part
ddb9e082454e34d15e9554f07c0896a1e77f4a76932135e55b681dd878cd2faf  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/bitcoin-e8e0e69c7d54-arm64-apple-darwin-unsigned.tar.gz
00624afcfe991691b065c5fb2f3b61cd280d3510d99e2eb0a3b79c4fd7c0e05f  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/bitcoin-e8e0e69c7d54-arm64-apple-darwin-unsigned.zip
914eec811f929632d03028c9c65cb5060275416bd4fda34afe4ec638c556957d  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/bitcoin-e8e0e69c7d54-arm64-apple-darwin.tar.gz
9311667d7fd23bcc6a2cdd7d745f3e4bec19a4a25e6a76cd1a88822060a0aa5b  guix-build-e8e0e69c7d54/output/dist-archive/bitcoin-e8e0e69c7d54.tar.gz
2c76f1ea6058dba7e8a4c185460ddfd97f4f73bcab7de83a16fc095b58431b76  guix-build-e8e0e69c7d54/output/powerpc64-linux-gnu/SHA256SUMS.part
09ab6835c1a28077e8659cc8cf9a1277e2180c6dfcc0d38450ffb30da23ad532  guix-build-e8e0e69c7d54/output/powerpc64-linux-gnu/bitcoin-e8e0e69c7d54-powerpc64-linux-gnu-debug.tar.gz
19570b69b520e385f9ba061a05e48da8cd6c6e36a282938bebf70a6399df731a  guix-build-e8e0e69c7d54/output/powerpc64-linux-gnu/bitcoin-e8e0e69c7d54-powerpc64-linux-gnu.tar.gz
2d955ef2f481a053d41143fc5462f1153d54e85f95ce7252696fd9957b4b4ddc  guix-build-e8e0e69c7d54/output/riscv64-linux-gnu/SHA256SUMS.part
aefa2475f1ed669daf4f43a62e660afc20c1eda0b75638a6668d152377949159  guix-build-e8e0e69c7d54/output/riscv64-linux-gnu/bitcoin-e8e0e69c7d54-riscv64-linux-gnu-debug.tar.gz
5067e2ecfc566a00a8ddc438dd3b73dd9db3281e6935a57ee833660aee5e548b  guix-build-e8e0e69c7d54/output/riscv64-linux-gnu/bitcoin-e8e0e69c7d54-riscv64-linux-gnu.tar.gz
748c7c1c0e23609fe0bf0e20f98943b9fe6a562283f17bde64662e7a7213630a  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/SHA256SUMS.part
a473c866208da7957e87a03d65cf7163d1ddb9a8fb8c01027c11c94535061c91  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/bitcoin-e8e0e69c7d54-x86_64-apple-darwin-unsigned.tar.gz
d9fa3384e48b7324828a705713b3e037fa086a97ec2945264f674927cf95a1a0  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/bitcoin-e8e0e69c7d54-x86_64-apple-darwin-unsigned.zip
652ea0e49bf7c388630db97a6767ccfd79aed2a10a9e2b72496b63709aa23a82  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/bitcoin-e8e0e69c7d54-x86_64-apple-darwin.tar.gz
8bc684f92865fd077d41a89d67c4f875eb591f03a5e7c5d94ef011fd9edceb5c  guix-build-e8e0e69c7d54/output/x86_64-linux-gnu/SHA256SUMS.part
cd8ea708d39d36e48b8d477808bb171ab44a5e8131394a0f9890cbe0649b482c  guix-build-e8e0e69c7d54/output/x86_64-linux-gnu/bitcoin-e8e0e69c7d54-x86_64-linux-gnu-debug.tar.gz
3f309bf1534c9815657769d0ec69bd15ee32866bbce177014c2ba9218ab391fc  guix-build-e8e0e69c7d54/output/x86_64-linux-gnu/bitcoin-e8e0e69c7d54-x86_64-linux-gnu.tar.gz
3bc2edcd65991dbba1ad1683e0b788a0638b40d647e5cd5fed4ffedb433588c9  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/SHA256SUMS.part
3328c85683a64a12c0c47e777a6a46721176d1543d91ccf9f83573c9eaaa4333  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64-debug.zip
30c2026fd1fba1d2cc92426b460f32032899f6dbe1826e89535ed516d609bbab  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64-setup-unsigned.exe
d805adfc7bae7265c0ef9af24f870617d4c502d7674275c089d5febb4baf92ff  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64-unsigned.tar.gz
8aab385c0ca5b0c8a2d980a40e41da5d51a9fa1f61c210cb92159ca95d84fa2c  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64.zip
```

**Comment by TheCharlatan** [comment]
Guix build (aarch64):
```
628ce0b4e73c8024a3b74fb17c83b20e54ebcc8079c49aead6f84de7cae6caa8  guix-build-e8e0e69c7d54/output/aarch64-linux-gnu/SHA256SUMS.part
47fdae9eab52cdfac83c2c18bb712521f24fdbd66caae5741f0bf4d0ef590c3b  guix-build-e8e0e69c7d54/output/aarch64-linux-gnu/bitcoin-e8e0e69c7d54-aarch64-linux-gnu-debug.tar.gz
4af831aeea939c0c006a84ca541c342dee6a7ad0141a68a092d800ec56307463  guix-build-e8e0e69c7d54/output/aarch64-linux-gnu/bitcoin-e8e0e69c7d54-aarch64-linux-gnu.tar.gz
c6bde599fa9e2376476222a41f74f19c96289e872bce24b4847adcd93055fe5e  guix-build-e8e0e69c7d54/output/arm-linux-gnueabihf/SHA256SUMS.part
fbb1d008f7890d9f8e31735af372904aa47706ad967e8ec4ff3ccebe706a6dc9  guix-build-e8e0e69c7d54/output/arm-linux-gnueabihf/bitcoin-e8e0e69c7d54-arm-linux-gnueabihf-debug.tar.gz
b363b970a9c9a7683fcda6f427c0f2c08fdd26c57cf1af859632a39091e8cd54  guix-build-e8e0e69c7d54/output/arm-linux-gnueabihf/bitcoin-e8e0e69c7d54-arm-linux-gnueabihf.tar.gz
4c2658d8a66dba960bc3f372a64b792fd37a1e9b3f98e1e10c7b05f324e7d9c5  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/SHA256SUMS.part
ddb9e082454e34d15e9554f07c0896a1e77f4a76932135e55b681dd878cd2faf  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/bitcoin-e8e0e69c7d54-arm64-apple-darwin-unsigned.tar.gz
00624afcfe991691b065c5fb2f3b61cd280d3510d99e2eb0a3b79c4fd7c0e05f  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/bitcoin-e8e0e69c7d54-arm64-apple-darwin-unsigned.zip
914eec811f929632d03028c9c65cb5060275416bd4fda34afe4ec638c556957d  guix-build-e8e0e69c7d54/output/arm64-apple-darwin/bitcoin-e8e0e69c7d54-arm64-apple-darwin.tar.gz
9311667d7fd23bcc6a2cdd7d745f3e4bec19a4a25e6a76cd1a88822060a0aa5b  guix-build-e8e0e69c7d54/output/dist-archive/bitcoin-e8e0e69c7d54.tar.gz
2c76f1ea6058dba7e8a4c185460ddfd97f4f73bcab7de83a16fc095b58431b76  guix-build-e8e0e69c7d54/output/powerpc64-linux-gnu/SHA256SUMS.part
09ab6835c1a28077e8659cc8cf9a1277e2180c6dfcc0d38450ffb30da23ad532  guix-build-e8e0e69c7d54/output/powerpc64-linux-gnu/bitcoin-e8e0e69c7d54-powerpc64-linux-gnu-debug.tar.gz
19570b69b520e385f9ba061a05e48da8cd6c6e36a282938bebf70a6399df731a  guix-build-e8e0e69c7d54/output/powerpc64-linux-gnu/bitcoin-e8e0e69c7d54-powerpc64-linux-gnu.tar.gz
2d955ef2f481a053d41143fc5462f1153d54e85f95ce7252696fd9957b4b4ddc  guix-build-e8e0e69c7d54/output/riscv64-linux-gnu/SHA256SUMS.part
aefa2475f1ed669daf4f43a62e660afc20c1eda0b75638a6668d152377949159  guix-build-e8e0e69c7d54/output/riscv64-linux-gnu/bitcoin-e8e0e69c7d54-riscv64-linux-gnu-debug.tar.gz
5067e2ecfc566a00a8ddc438dd3b73dd9db3281e6935a57ee833660aee5e548b  guix-build-e8e0e69c7d54/output/riscv64-linux-gnu/bitcoin-e8e0e69c7d54-riscv64-linux-gnu.tar.gz
748c7c1c0e23609fe0bf0e20f98943b9fe6a562283f17bde64662e7a7213630a  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/SHA256SUMS.part
a473c866208da7957e87a03d65cf7163d1ddb9a8fb8c01027c11c94535061c91  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/bitcoin-e8e0e69c7d54-x86_64-apple-darwin-unsigned.tar.gz
d9fa3384e48b7324828a705713b3e037fa086a97ec2945264f674927cf95a1a0  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/bitcoin-e8e0e69c7d54-x86_64-apple-darwin-unsigned.zip
652ea0e49bf7c388630db97a6767ccfd79aed2a10a9e2b72496b63709aa23a82  guix-build-e8e0e69c7d54/output/x86_64-apple-darwin/bitcoin-e8e0e69c7d54-x86_64-apple-darwin.tar.gz
8bc684f92865fd077d41a89d67c4f875eb591f03a5e7c5d94ef011fd9edceb5c  guix-build-e8e0e69c7d54/output/x86_64-linux-gnu/SHA256SUMS.part
cd8ea708d39d36e48b8d477808bb171ab44a5e8131394a0f9890cbe0649b482c  guix-build-e8e0e69c7d54/output/x86_64-linux-gnu/bitcoin-e8e0e69c7d54-x86_64-linux-gnu-debug.tar.gz
3f309bf1534c9815657769d0ec69bd15ee32866bbce177014c2ba9218ab391fc  guix-build-e8e0e69c7d54/output/x86_64-linux-gnu/bitcoin-e8e0e69c7d54-x86_64-linux-gnu.tar.gz
3bc2edcd65991dbba1ad1683e0b788a0638b40d647e5cd5fed4ffedb433588c9  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/SHA256SUMS.part
3328c85683a64a12c0c47e777a6a46721176d1543d91ccf9f83573c9eaaa4333  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64-debug.zip
30c2026fd1fba1d2cc92426b460f32032899f6dbe1826e89535ed516d609bbab  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64-setup-unsigned.exe
d805adfc7bae7265c0ef9af24f870617d4c502d7674275c089d5febb4baf92ff  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64-unsigned.tar.gz
8aab385c0ca5b0c8a2d980a40e41da5d51a9fa1f61c210cb92159ca95d84fa2c  guix-build-e8e0e69c7d54/output/x86_64-w64-mingw32/bitcoin-e8e0e69c7d54-win64.zip
```

**Review by TheCharlatan — APPROVED** [review]
lgtm

**Comment by hebasto** [comment]
@TheCharlatan

Thank you for your review!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Pull request closed without merging**
