### PR TITLE
Include the *werror_flag in TryAppend*Flags compiler cache

### PR DESCRIPTION
**Pull request by l0rinc**
Trigger recompilation when `working_linker_werror_flag`or `working_compiler_werror_flag` are changed since it can affect the outcome.

Trigger recompilation when `working_linker_werror_flag` or `working_compiler_werror_flag` are changed, as these modifications [can affect the build outcome](https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1711409392).

##### Steps to Reproduce on a Mac (the OR fix is not relate to a Mac, but it's easier to reproduce the error there):
1. compile for fuzzing, i,e,
```bash
cmake -B build_fuzz \
 -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" \
 -DBUILD_FOR_FUZZING=ON \
 -DSANITIZERS=undefined,address,fuzzer
```
2. Modify `try_append_linker_flag("-Wl,-fatal_warnings" VAR working_linker_werror_flag)` to include an additional flag (e.g., `-Wl,-no_warn_duplicate_libraries`).
3. Run the command again - should pass with the PR, shouldn't pass without the pr (only by manually deleting the `build` fodle)

### CODE REVIEW

**Comment by hebasto** [comment]
Please rebase. The staging branch has been just updated in https://github.com/hebasto/bitcoin/pull/318.

**Comment by paplorinc** [comment]
> Please rebase. The staging branch has been just updated in #318.

done

**Comment by hebasto** [comment]
> Trigger recompilation when `working_linker_werror_flag`or `working_compiler_werror_flag` are changed

What are the use cases for that?

**Comment by paplorinc** [comment]
Compiling the same code with different flags

**Comment by hebasto** [comment]
> Compiling the same code with different flags 

Flags that make a compiler/linker treat warnings as errors are specific to a particular toolchain. It does not depend on the user, does it?

**Comment by paplorinc** [comment]
I'm not exactly sure what you're referring to.
This fixed my observation about https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1711409392 where adding the -no_warn_duplicate_libraries flag in the source code only fixed fuzzing after I manually deleted the build_fuzz folder (i.e. compilation wasn't reattempeted with different flags).
After this PR these kinds of edits are detected and the cache is properly invalidated.

**Comment by hebasto** [comment]
The build system is not intended to be modified by regular users or developers unless they are working on the build system itself. Users can modify compiler and linker flags using standard CMake variables or, in special cases, project-specific `APPEND_*FLAGS`.

**Comment by paplorinc** [comment]
> unless they are working on the build system itself

Yes, that's what happened to me, hence this PR.

I have also opened https://gitlab.kitware.com/cmake/cmake/-/issues/26207, though I still think the issue is on our side, we should include all inputs into the cache key (if we want proper cache invalidation), not just the source code.

**Comment by l0rinc** [comment]
> What are the exact steps to reproduce?

While trying to understand why fuzzing wasn't working with cmake on my mac, I have noticed that changing
>  try_append_linker_flag("-Wl,-fatal_warnings" VAR working_linker_werror_flag)

to e.g.

>  try_append_linker_flag("-Wl,-no_warn_duplicate_libraries,-fatal_warnings" VAR working_linker_werror_flag)

i.e. adding `-no_warn_duplicate_libraries` to the `working_linker_werror_flag` didn't retrigger the previous failing compilation - but deleting the `build` folder and retrying did (see https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1710280041).

**Review by pablomartin4btc — COMMENTED** [review]
tACK 0c9d36d725a8d5a3bbdc53dc985d9245b1279ccb

I managed to reproduce the issue on macOS (also checking not happening on linux) but running the same command on your branch (without @hebasto workaround `-DAPPEND_LDFLAGS="-Wl,-no_warn_duplicate_libraries"`) does't get it fixed, unless I'm missing something (?):

```

git clone --depth=1 --branch l0rinc/werror_flag https://github.com/l0rinc//bitcoin.git bitcoin-cmake

cd bitcoin-make

cmake -B build_fuzz -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DBUILD_FOR_FUZZING=ON -DSANITIZERS=undefined,address,fuzzer

-- The CXX compiler identification is Clang 18.1.8
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SQLite3: /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include (found suitable version "3.43.2", minimum required is "3.7.17")
CMake Warning at CMakeLists.txt:243 (message):
  BUILD_FOR_FUZZING=ON will disable all other targets and force
  BUILD_FUZZ_BINARY=ON.


-- Performing Test CXX_SUPPORTS__WERROR
-- Performing Test CXX_SUPPORTS__WERROR - Success
-- Setting build type to "RelWithDebInfo" as none was specified
-- Performing Test CXX_SUPPORTS__G3
-- Performing Test CXX_SUPPORTS__G3 - Success
-- Performing Test LINKER_SUPPORTS__G3
-- Performing Test LINKER_SUPPORTS__G3 - Success
-- Performing Test CXX_SUPPORTS__FTRAPV
-- Performing Test CXX_SUPPORTS__FTRAPV - Success
-- Performing Test LINKER_SUPPORTS__FTRAPV
-- Performing Test LINKER_SUPPORTS__FTRAPV - Success
-- Performing Test LINKER_SUPPORTS__WL__FATAL_WARNINGS
-- Performing Test LINKER_SUPPORTS__WL__FATAL_WARNINGS - Success
-- Performing Test LINKER_SUPPORTS__WL__DEAD_STRIP
-- Performing Test LINKER_SUPPORTS__WL__DEAD_STRIP - Success
-- Performing Test LINKER_SUPPORTS__WL__DEAD_STRIP_DYLIBS
-- Performing Test LINKER_SUPPORTS__WL__DEAD_STRIP_DYLIBS - Success
-- Performing Test LINKER_SUPPORTS__WL__HEADERPAD_MAX_INSTALL_NAMES
-- Performing Test LINKER_SUPPORTS__WL__HEADERPAD_MAX_INSTALL_NAMES - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test CXX_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER
-- Performing Test CXX_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER - Success
-- Performing Test LINKER_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER_339c
-- Performing Test LINKER_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER_339c - Failed
CMake Error at CMakeLists.txt:393 (message):
  Linker did not accept requested flags, you are missing required libraries.


-- Configuring incomplete, errors occurred!


```

**Comment by l0rinc** [comment]
@pablomartin4btc, thanks for reviewing!

To be able to reproduce it, try to create the same fuzzing by first reproducing at, after which don't manually invalidate any cache (e.g. by deleting the build folder), but rather:
```diff
diff --git a/cmake/module/TryAppendLinkerFlag.cmake b/cmake/module/TryAppendLinkerFlag.cmake
--- a/cmake/module/TryAppendLinkerFlag.cmake	(revision 687a10ba93917646440993804998deaf58ae3f6b)
+++ b/cmake/module/TryAppendLinkerFlag.cmake	(date 1724428115452)
@@ -79,7 +79,7 @@
 if(MSVC)
   try_append_linker_flag("/WX" VAR working_linker_werror_flag)
 elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
-  try_append_linker_flag("-Wl,-fatal_warnings" VAR working_linker_werror_flag)
+  try_append_linker_flag("-Wl,-no_warn_duplicate_libraries,-fatal_warnings" VAR working_linker_werror_flag)
 else()
   try_append_linker_flag("-Wl,--fatal-warnings" VAR working_linker_werror_flag)
 endif()
```
and rerun the
```bash
cmake -B build_fuzz -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DBUILD_FOR_FUZZING=ON -DSANITIZERS=undefined,address,fuzzer
```

command with/without the caching fix introduces in this commit.
It should still fail first, but if you delete the `build` folder and rerun, it should pass.

**Comment by pablomartin4btc** [comment]
Ok, if I repro de error, update `cmake/module/TryAppendLinkerFlag.cmake` and rerun, it passes.
Now, with this PR/ branch, even if it fails the first time, deleting the folder and rerunning it not passes. What I'm doing wrong here?

**Comment by l0rinc** [comment]
Could you please share the commands and diff you were using?

**Comment by pablomartin4btc** [comment]
> Could you please share the commands and diff you were using?

```
git clone --depth=1 --branch l0rinc/werror_flag https://github.com/l0rinc//bitcoin.git bitcoin-cmake
cd bitcoin-make
cmake -B build_fuzz -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DBUILD_FOR_FUZZING=ON -DSANITIZERS=undefined,address,fuzzer
...
-- Performing Test CXX_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER
-- Performing Test CXX_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER - Success
-- Performing Test LINKER_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER_339c
-- Performing Test LINKER_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER_339c - Failed
CMake Error at CMakeLists.txt:393 (message):
  Linker did not accept requested flags, you are missing required libraries.


-- Configuring incomplete, errors occurred!

rm -rf build_fuzz

cmake -B build_fuzz -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DBUILD_FOR_FUZZING=ON -DSANITIZERS=undefined,address,fuzzer
...
-- Performing Test CXX_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER
-- Performing Test CXX_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER - Success
-- Performing Test LINKER_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER_339c
-- Performing Test LINKER_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER_339c - Failed
CMake Error at CMakeLists.txt:393 (message):
  Linker did not accept requested flags, you are missing required libraries.


-- Configuring incomplete, errors occurred!
```

**Comment by l0rinc** [comment]
The PR itself does not directly fix the issue of `Linker did not accept requested flags`.
Instead, it addresses the problem where even after applying the fix (i.e., `-no_warn_duplicate_libraries`), it only worked if the cache was invalidated (i.e., by deleting the `build_fuzz` folder).

After this change, applying the fix (as shown in the diff above) should automatically invalidate the cache and work without needing to delete te `build_fuzz` folder.

**Comment by pablomartin4btc** [comment]
Ok got you now, thanks!

I still had to re-read the PR to find some important statements ([eg](https://github.com/hebasto/bitcoin/pull/319#issuecomment-2282198428) "_After this PR these kinds of edits are detected and the cache is properly invalidated._").

So still we need to change `try_append_linker_flag` adding `-no_warn_duplicate_libraries`. Perhaps you need to clarify it in the description of the PR, now it obvious to me too but got confused, sorry, and that this happens only on macOS (so far) or you need to change the `try_append_linker_flag` line for the specific platform.

If I do that (try_append*) in `cmake_staging` or #30454, without making it fail first, it compiles, but sure you don't in advance if that's going to happend and I see the only way there, if it fails first, it's deleting the build folder (also perhaps adding it to the PR description).

Since I'm here I'm checking some runtime errors I got on macOS running the `fuzz` so I need to check it against autotools and other OSs.

**Comment by l0rinc** [comment]
Thanks @pablomartin4btc, updated the readme.

**Comment by l0rinc** [comment]
Might be invalidated by https://github.com/hebasto/bitcoin/pull/340

**Comment by hebasto** [comment]
Since https://github.com/bitcoin/bitcoin/pull/30454 has been merged, further development in this repository no longer makes sense. Please consider moving this PR to the main repository.

**Pull request closed without merging**
