### PR TITLE
cmake: Revert CMake's way to handle definitions

### PR DESCRIPTION
**Pull request by hebasto**
This PR adjusts CMake scripts in such a way that makes removing `#include <config/bitcoin-config.h>`  from sources is unnecessary.

Effectively, this makes Autotools and CMake builds comparable.

Addresses https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1679674217 and https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1679842517.

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @maflcko @theuni @fanquake @TheCharlatan :)

**Comment by theuni** [comment]
Are these going to remain as reverts on top of the original changes?

**Comment by hebasto** [comment]
> Are these going to remain as reverts on top of the original changes?

No. I'm going to squash these commits with the past relevant commits.

**Comment by hebasto** [comment]
Rebased on top of the merged https://github.com/hebasto/bitcoin/pull/268.

**Comment by hebasto** [comment]
> > Are these going to remain as reverts on top of the original changes?
> 
> No. I'm going to squash these commits with the past relevant commits during the next sync/rebase round.

The commit messages have been updated to reflect this intention.

**Review by theuni — APPROVED** [review]
I believe this is correct. Hard to tell without doing a full rebase, but the only related code-change in the diff from pre-cmake is src/qt/guiutil.cpp, which had its bitcoin-config.h include removed for the static plugin change.

If there are any mistakes here, I think they'll be obvious post-rebase.

utACK f440d335a0c4bf0ed896be61d64ba71daa160f06

**Pull request merged**
