### PR TITLE
cmake: Drop no longer needed code to handle ENV unsetting

### PR DESCRIPTION
**Pull request by hebasto**
The https://github.com/bitcoin/bitcoin/pull/30451 allows to simplify the CMake code.

This PR drops the code that handles ENV unsetting:
- in `depends/toolchain.cmake.in`
- in `cmake/module/Maintenance.cmake`

### CODE REVIEW

**Comment by hebasto** [comment]
cc @fanquake @TheCharlatan

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
0ccc235b56b284c3d07a9628316e343b3eaaf23a7989280b10cebda680805d42  guix-build-9dc09cc4e893/output/arm64-apple-darwin/SHA256SUMS.part
732ce22eb1af331669775523c9d3a6cce0ad9f6731cb86c40390dcc5655e20de  guix-build-9dc09cc4e893/output/arm64-apple-darwin/bitcoin-9dc09cc4e893-arm64-apple-darwin-unsigned.tar.gz
c9e88b741476f5dbb4bd489dd04b83f9ca7c79d32bab1d85820e830453dcf54a  guix-build-9dc09cc4e893/output/arm64-apple-darwin/bitcoin-9dc09cc4e893-arm64-apple-darwin-unsigned.zip
62a805d24bcd60cc14f2789c240537432798f9d06ab0321c0d6735d54be8b3aa  guix-build-9dc09cc4e893/output/arm64-apple-darwin/bitcoin-9dc09cc4e893-arm64-apple-darwin.tar.gz
77de052b8efedabe7b102f37651faea1b8d2822dc15f53b0038630ee85756023  guix-build-9dc09cc4e893/output/dist-archive/bitcoin-9dc09cc4e893.tar.gz
cf3cae7359c17c6b755c77351126c8bcb184ce5219e6a6b9fef3b8a8393015d6  guix-build-9dc09cc4e893/output/x86_64-apple-darwin/SHA256SUMS.part
3d9d516c4a35b3b621083b836874ad9b03bd43679fd2ef6ba9d8d63771becfda  guix-build-9dc09cc4e893/output/x86_64-apple-darwin/bitcoin-9dc09cc4e893-x86_64-apple-darwin-unsigned.tar.gz
64a99116c667650b46544935a97f6f56456fc50e09719dcdcd9a43ad9b6ed86a  guix-build-9dc09cc4e893/output/x86_64-apple-darwin/bitcoin-9dc09cc4e893-x86_64-apple-darwin-unsigned.zip
e72b08fc49f86124cf86dd817443617e90661d62017017ba5fad865fe26b26e0  guix-build-9dc09cc4e893/output/x86_64-apple-darwin/bitcoin-9dc09cc4e893-x86_64-apple-darwin.tar.gz
```

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
5ddf1e5eefab44bd2fdc8fb27e952a340eb58fd76a286680718ab6564dce7e32  guix-build-4edb2e9424d1/output/arm64-apple-darwin/SHA256SUMS.part
d9fec1b122cb9790386c19ec3ba29bda32497403c1936dc795ce8a59a9d29f19  guix-build-4edb2e9424d1/output/arm64-apple-darwin/bitcoin-4edb2e9424d1-arm64-apple-darwin-unsigned.tar.gz
19c129e23e00b447058731a54ea7a5ae17b4ec254615404d699001384e2cfd9d  guix-build-4edb2e9424d1/output/arm64-apple-darwin/bitcoin-4edb2e9424d1-arm64-apple-darwin-unsigned.zip
96cf975c6dc4613e8f834409843f4ad9e0866afc819f609cc5ebde0c3d8c431f  guix-build-4edb2e9424d1/output/arm64-apple-darwin/bitcoin-4edb2e9424d1-arm64-apple-darwin.tar.gz
3b3dceefb41401c9ab23293341d7358b3d7cbede5e94d8de17269a3b36623880  guix-build-4edb2e9424d1/output/dist-archive/bitcoin-4edb2e9424d1.tar.gz
b4bf90184688fef61c99a99bde1d681f125302907f36631934c396c4aef81396  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/SHA256SUMS.part
403c6fa7c8dc01beb243437ea466186dbc4ed09e64e4cfac36181dde1479ec9f  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/bitcoin-4edb2e9424d1-x86_64-apple-darwin-unsigned.tar.gz
d23d3fbe5404453d7ef45fc6cff8bdf1eca4e5ed799760cf556b1603f22feddc  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/bitcoin-4edb2e9424d1-x86_64-apple-darwin-unsigned.zip
3fc51c53968601434779ed607fd7243c796e4b9caa93dcc00b499efb81a0b762  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/bitcoin-4edb2e9424d1-x86_64-apple-darwin.tar.gz
```

**Comment by m3dwards** [comment]
ACK 4edb2e9424d177d3861bd5a558c55198e262cf73

Much simpler

x86_64 guix build

```shell
5ddf1e5eefab44bd2fdc8fb27e952a340eb58fd76a286680718ab6564dce7e32  guix-build-4edb2e9424d1/output/arm64-apple-darwin/SHA256SUMS.part
d9fec1b122cb9790386c19ec3ba29bda32497403c1936dc795ce8a59a9d29f19  guix-build-4edb2e9424d1/output/arm64-apple-darwin/bitcoin-4edb2e9424d1-arm64-apple-darwin-unsigned.tar.gz
19c129e23e00b447058731a54ea7a5ae17b4ec254615404d699001384e2cfd9d  guix-build-4edb2e9424d1/output/arm64-apple-darwin/bitcoin-4edb2e9424d1-arm64-apple-darwin-unsigned.zip
96cf975c6dc4613e8f834409843f4ad9e0866afc819f609cc5ebde0c3d8c431f  guix-build-4edb2e9424d1/output/arm64-apple-darwin/bitcoin-4edb2e9424d1-arm64-apple-darwin.tar.gz
3b3dceefb41401c9ab23293341d7358b3d7cbede5e94d8de17269a3b36623880  guix-build-4edb2e9424d1/output/dist-archive/bitcoin-4edb2e9424d1.tar.gz
b4bf90184688fef61c99a99bde1d681f125302907f36631934c396c4aef81396  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/SHA256SUMS.part
403c6fa7c8dc01beb243437ea466186dbc4ed09e64e4cfac36181dde1479ec9f  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/bitcoin-4edb2e9424d1-x86_64-apple-darwin-unsigned.tar.gz
d23d3fbe5404453d7ef45fc6cff8bdf1eca4e5ed799760cf556b1603f22feddc  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/bitcoin-4edb2e9424d1-x86_64-apple-darwin-unsigned.zip
3fc51c53968601434779ed607fd7243c796e4b9caa93dcc00b499efb81a0b762  guix-build-4edb2e9424d1/output/x86_64-apple-darwin/bitcoin-4edb2e9424d1-x86_64-apple-darwin.tar.gz
```

**Pull request merged**
