### PR TITLE
cmake: Add `GPROF` configuration option

### PR DESCRIPTION
**Pull request by hebasto**
This PR adds a new `GPROF` configuration option, which is an analogue of Autotools' `--enable-gprof`.

Due to _"`-pg` is incompatible with `-pie`"_ restriction, Autotools require to disable hardening, because `-fPIE -pie` flags are set only when hardening enabled.

In CMake, those flags are controlled by the `POSITION_INDEPENDENT_CODE` property. Therefore, no need to disable hardening.

I believe that such a difference is acceptable for performance analysis.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @theuni

**Review by fanquake — COMMENTED** [review]
> Due to "-pg is incompatible with -pie" restriction, Autotools require to disable hardening, because -fPIE -pie flags are set only when hardening enabled.
> In CMake, those flags are controlled by the POSITION_INDEPENDENT_CODE property. Therefore, no need to disable hardening.
> I believe that such a difference is acceptable for performance analysis.

What differences did you see when doing profiling with this branch?

**Comment by hebasto** [comment]
As I mentioned during the recent call, I suggest to consider not implementing this option for the following reasons:
1. It is simple and straightforward for the user to pass additional `-pg` or `-pg -no-pie` flags.
2. CMake's [abstraction](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html) of the position independent code bounds [together](https://cmake.org/cmake/help/latest/policy/CMP0083.html) applying needed flags during compile and link steps, which makes non-trivial to build PIC code for libbitcoinkernel shared library in the combination with non-PIE executables.

The `--enable-werror` option [also](https://gist.github.com/hebasto/028359b0d6c892343660219c22c34778) is about applying the only flag, but its usage is very wide including the CI etc.

**Comment by theuni** [comment]
> As I mentioned during the recent call, I suggest to consider not implementing this option for the following reasons:

+1. I'm pretty sure I actually ported the gprof features from the pre-autotools buildsystem simply because they were already there. I don't think there's a need to move it forward unless someone has a good reason.

**Comment by hebasto** [comment]
> > As I mentioned during the recent call, I suggest to consider not implementing this option for the following reasons:
> 
> +1. I'm pretty sure I actually ported the gprof features from the pre-autotools buildsystem simply because they were already there. I don't think there's a need to move it forward unless someone has a good reason.

Closing. The ["Autotools vs CMake Feature Parity Table"](https://gist.github.com/hebasto/2ef97d3a726bfce08ded9df07f7dab5e) has ben adjusted.

**Comment by fanquake** [comment]
> I'm pretty sure I actually ported the gprof features from the pre-autotools buildsystem simply because they were already there.

I might be missing something, but to clarify, they were added by someone else ~5 years ago?

**Comment by theuni** [comment]
Yes, sorry, I had this mixed up with gcov/lcov.

**Pull request closed without merging**
