### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/commit/028cc4c8c15afee8b82c04f1ae088e64f2841be4) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/ee367170cb2acf82b6ff8e0ccdbc1cce09730662) branch, which includes the main build system changes, with the squashed "!fixup" commits.

Steps to reproduce:
1. Run the command as follows:
```
git checkout 028cc4c8c15afee8b82c04f1ae088e64f2841be4
git rebase -i --autosquash ee367170cb2acf82b6ff8e0ccdbc1cce09730662
```
There is a conflict that has to be resolved.

2. Squash "[FIXUP]" commits that were not handled automatically (there must be a zero-diff change).

2. Port build system changes from:
- https://github.com/bitcoin/bitcoin/pull/28209

### CODE REVIEW

**Comment by hebasto** [comment]
Drafted until https://github.com/hebasto/bitcoin/pull/335 is landed.

**Comment by hebasto** [comment]
> Drafted until #335 is landed.

Ready fro review again!

**Comment by m3dwards** [comment]
ACK 818a3c07fb48e4f7fdaf5640f3987d47280f54d0

Clean diff between op process and `240816-linear`

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
450e47fcd499ff52b36490ec7afda903f4e23d7343f73cf28c8aa14d84759ece  guix-build-818a3c07fb48/output/aarch64-linux-gnu/SHA256SUMS.part
406714827e2904be7b865ba03669f0a40bb49714334578c1813581f5543db1c1  guix-build-818a3c07fb48/output/aarch64-linux-gnu/bitcoin-818a3c07fb48-aarch64-linux-gnu-debug.tar.gz
3cf9aa25ea417730beea258799ae034c8699848e09928d04365e202e3df4d78d  guix-build-818a3c07fb48/output/aarch64-linux-gnu/bitcoin-818a3c07fb48-aarch64-linux-gnu.tar.gz
064e9873195ea6b81aebd91f50b7675823090467f39fd27cc2c6cb2964843a5e  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/SHA256SUMS.part
319db0eb58f29ea0c94593c59f9d92acbd49475519b0860b24be1fd615414453  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/bitcoin-818a3c07fb48-arm-linux-gnueabihf-debug.tar.gz
1a149e92d64d1f05f3475e745c88629fd9b63149d0e7edf3aaa754acf771a819  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/bitcoin-818a3c07fb48-arm-linux-gnueabihf.tar.gz
8e85461e4f3eab6f89ca008f4017e75a7328b2e2c6c842362168fb78fe95243a  guix-build-818a3c07fb48/output/arm64-apple-darwin/SHA256SUMS.part
50affef2f0d0b40c208801a48be5abb04a10fa1c8097424aba9429efeae96b6a  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin-unsigned.tar.gz
9fc625daa494396ff8f71b8dde060b1a0e90e01c94f6e5304e4bdc95dad92a3f  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin-unsigned.zip
745c339ec4d300a19a0d70c44fa047d074c321ddfc47039d6fb625957b96b5f5  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin.tar.gz
60921b3be448ff2e128be98e63a940c7f5327e10def6b58cf36665cd157967ab  guix-build-818a3c07fb48/output/dist-archive/bitcoin-818a3c07fb48.tar.gz
56f75f7b811da2fc209e41155043e0765938128934964535c12c0b2992cf3484  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/SHA256SUMS.part
fc9afedb71bc5a1bde7cf08ed937dc68cca76faadf17f654e8d0b0d276070909  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/bitcoin-818a3c07fb48-powerpc64-linux-gnu-debug.tar.gz
6a67d618819bf8a78785d4f795b25bc37f756ff1f859d8f06b505422452f6b4e  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/bitcoin-818a3c07fb48-powerpc64-linux-gnu.tar.gz
7b09ea93f4778eb81d1b29d3c26b08f1c9c5de4fb4453536651bf1c2ece1c66b  guix-build-818a3c07fb48/output/riscv64-linux-gnu/SHA256SUMS.part
118c1fc1cc5973d623ca0a4d96973b5c4e8f0d2dc1354b09d5244ec2df01f236  guix-build-818a3c07fb48/output/riscv64-linux-gnu/bitcoin-818a3c07fb48-riscv64-linux-gnu-debug.tar.gz
9d2794fb6f00517ba3ab279e50ecd42d9e25dd4fd5e61b5f8fb31fc81e9c5931  guix-build-818a3c07fb48/output/riscv64-linux-gnu/bitcoin-818a3c07fb48-riscv64-linux-gnu.tar.gz
d6d9910d4c76b553c69d55418b0f577937beef60b4952e241e7a389df5918dc9  guix-build-818a3c07fb48/output/x86_64-apple-darwin/SHA256SUMS.part
8b7409b6c3eaf5425b58055830c506c96a60b96a658df7b41f08ccd4d2cfe7ef  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin-unsigned.tar.gz
86443fa7f87c38ec127ac88abe73fc9bcc8ae17adc87345daf930509ebe22f3a  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin-unsigned.zip
ffcf5040db9c5b182df7b84dc41fba79231d1274b7759b87cd72f680b1c3340a  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin.tar.gz
54292290975c5ff1028784dfce5fc4726a94c260665051fe65c4c521e8d0247a  guix-build-818a3c07fb48/output/x86_64-linux-gnu/SHA256SUMS.part
a28cd6961446b3302d6a1410a14f597f81839116d09b169709e00f9d783d430f  guix-build-818a3c07fb48/output/x86_64-linux-gnu/bitcoin-818a3c07fb48-x86_64-linux-gnu-debug.tar.gz
cf46aae7ce6d959111bd8516093a9bd6aa3a11f0c1c8ae33a9de6bbb0767d333  guix-build-818a3c07fb48/output/x86_64-linux-gnu/bitcoin-818a3c07fb48-x86_64-linux-gnu.tar.gz
e6a780c7e9124b2b3423cdefa7ed6630f7fbf70a381e53d606580a9cca8a9f05  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/SHA256SUMS.part
d88527ec42dd21ba366148b926205d01ad06fcc2e44796c05f9cda53a7b7a3ad  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-debug.zip
0b6dec24b248b3e5b45188554842b24d5341a1321608087a6adaea16c7228e3e  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-setup-unsigned.exe
a0779f90be6a3b2e252c167892ce94158b47474e150565f3ea83862f7fc58862  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-unsigned.tar.gz
310d3e0d46a72d6040ff80712c65cb39c4cbbafd714ae69a6e12f9502b0b6853  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64.zip
```

**Review by TheCharlatan — APPROVED** [review]
lgtm

Guix builds (aarch64):
```
450e47fcd499ff52b36490ec7afda903f4e23d7343f73cf28c8aa14d84759ece  guix-build-818a3c07fb48/output/aarch64-linux-gnu/SHA256SUMS.part
406714827e2904be7b865ba03669f0a40bb49714334578c1813581f5543db1c1  guix-build-818a3c07fb48/output/aarch64-linux-gnu/bitcoin-818a3c07fb48-aarch64-linux-gnu-debug.tar.gz
3cf9aa25ea417730beea258799ae034c8699848e09928d04365e202e3df4d78d  guix-build-818a3c07fb48/output/aarch64-linux-gnu/bitcoin-818a3c07fb48-aarch64-linux-gnu.tar.gz
064e9873195ea6b81aebd91f50b7675823090467f39fd27cc2c6cb2964843a5e  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/SHA256SUMS.part
319db0eb58f29ea0c94593c59f9d92acbd49475519b0860b24be1fd615414453  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/bitcoin-818a3c07fb48-arm-linux-gnueabihf-debug.tar.gz
1a149e92d64d1f05f3475e745c88629fd9b63149d0e7edf3aaa754acf771a819  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/bitcoin-818a3c07fb48-arm-linux-gnueabihf.tar.gz
8e85461e4f3eab6f89ca008f4017e75a7328b2e2c6c842362168fb78fe95243a  guix-build-818a3c07fb48/output/arm64-apple-darwin/SHA256SUMS.part
50affef2f0d0b40c208801a48be5abb04a10fa1c8097424aba9429efeae96b6a  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin-unsigned.tar.gz
9fc625daa494396ff8f71b8dde060b1a0e90e01c94f6e5304e4bdc95dad92a3f  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin-unsigned.zip
745c339ec4d300a19a0d70c44fa047d074c321ddfc47039d6fb625957b96b5f5  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin.tar.gz
60921b3be448ff2e128be98e63a940c7f5327e10def6b58cf36665cd157967ab  guix-build-818a3c07fb48/output/dist-archive/bitcoin-818a3c07fb48.tar.gz
56f75f7b811da2fc209e41155043e0765938128934964535c12c0b2992cf3484  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/SHA256SUMS.part
fc9afedb71bc5a1bde7cf08ed937dc68cca76faadf17f654e8d0b0d276070909  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/bitcoin-818a3c07fb48-powerpc64-linux-gnu-debug.tar.gz
6a67d618819bf8a78785d4f795b25bc37f756ff1f859d8f06b505422452f6b4e  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/bitcoin-818a3c07fb48-powerpc64-linux-gnu.tar.gz
7b09ea93f4778eb81d1b29d3c26b08f1c9c5de4fb4453536651bf1c2ece1c66b  guix-build-818a3c07fb48/output/riscv64-linux-gnu/SHA256SUMS.part
118c1fc1cc5973d623ca0a4d96973b5c4e8f0d2dc1354b09d5244ec2df01f236  guix-build-818a3c07fb48/output/riscv64-linux-gnu/bitcoin-818a3c07fb48-riscv64-linux-gnu-debug.tar.gz
9d2794fb6f00517ba3ab279e50ecd42d9e25dd4fd5e61b5f8fb31fc81e9c5931  guix-build-818a3c07fb48/output/riscv64-linux-gnu/bitcoin-818a3c07fb48-riscv64-linux-gnu.tar.gz
d6d9910d4c76b553c69d55418b0f577937beef60b4952e241e7a389df5918dc9  guix-build-818a3c07fb48/output/x86_64-apple-darwin/SHA256SUMS.part
8b7409b6c3eaf5425b58055830c506c96a60b96a658df7b41f08ccd4d2cfe7ef  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin-unsigned.tar.gz
86443fa7f87c38ec127ac88abe73fc9bcc8ae17adc87345daf930509ebe22f3a  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin-unsigned.zip
ffcf5040db9c5b182df7b84dc41fba79231d1274b7759b87cd72f680b1c3340a  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin.tar.gz
54292290975c5ff1028784dfce5fc4726a94c260665051fe65c4c521e8d0247a  guix-build-818a3c07fb48/output/x86_64-linux-gnu/SHA256SUMS.part
a28cd6961446b3302d6a1410a14f597f81839116d09b169709e00f9d783d430f  guix-build-818a3c07fb48/output/x86_64-linux-gnu/bitcoin-818a3c07fb48-x86_64-linux-gnu-debug.tar.gz
cf46aae7ce6d959111bd8516093a9bd6aa3a11f0c1c8ae33a9de6bbb0767d333  guix-build-818a3c07fb48/output/x86_64-linux-gnu/bitcoin-818a3c07fb48-x86_64-linux-gnu.tar.gz
e6a780c7e9124b2b3423cdefa7ed6630f7fbf70a381e53d606580a9cca8a9f05  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/SHA256SUMS.part
d88527ec42dd21ba366148b926205d01ad06fcc2e44796c05f9cda53a7b7a3ad  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-debug.zip
0b6dec24b248b3e5b45188554842b24d5341a1321608087a6adaea16c7228e3e  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-setup-unsigned.exe
a0779f90be6a3b2e252c167892ce94158b47474e150565f3ea83862f7fc58862  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-unsigned.tar.gz
310d3e0d46a72d6040ff80712c65cb39c4cbbafd714ae69a6e12f9502b0b6853  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64.zip
```

**Comment by hebasto** [comment]
@m3dwards @TheCharlatan 

Thank you for your reviews!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Comment by m3dwards** [comment]
x86 guix build

```shell
450e47fcd499ff52b36490ec7afda903f4e23d7343f73cf28c8aa14d84759ece  guix-build-818a3c07fb48/output/aarch64-linux-gnu/SHA256SUMS.part
406714827e2904be7b865ba03669f0a40bb49714334578c1813581f5543db1c1  guix-build-818a3c07fb48/output/aarch64-linux-gnu/bitcoin-818a3c07fb48-aarch64-linux-gnu-debug.tar.gz
3cf9aa25ea417730beea258799ae034c8699848e09928d04365e202e3df4d78d  guix-build-818a3c07fb48/output/aarch64-linux-gnu/bitcoin-818a3c07fb48-aarch64-linux-gnu.tar.gz
064e9873195ea6b81aebd91f50b7675823090467f39fd27cc2c6cb2964843a5e  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/SHA256SUMS.part
319db0eb58f29ea0c94593c59f9d92acbd49475519b0860b24be1fd615414453  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/bitcoin-818a3c07fb48-arm-linux-gnueabihf-debug.tar.gz
1a149e92d64d1f05f3475e745c88629fd9b63149d0e7edf3aaa754acf771a819  guix-build-818a3c07fb48/output/arm-linux-gnueabihf/bitcoin-818a3c07fb48-arm-linux-gnueabihf.tar.gz
8e85461e4f3eab6f89ca008f4017e75a7328b2e2c6c842362168fb78fe95243a  guix-build-818a3c07fb48/output/arm64-apple-darwin/SHA256SUMS.part
50affef2f0d0b40c208801a48be5abb04a10fa1c8097424aba9429efeae96b6a  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin-unsigned.tar.gz
9fc625daa494396ff8f71b8dde060b1a0e90e01c94f6e5304e4bdc95dad92a3f  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin-unsigned.zip
745c339ec4d300a19a0d70c44fa047d074c321ddfc47039d6fb625957b96b5f5  guix-build-818a3c07fb48/output/arm64-apple-darwin/bitcoin-818a3c07fb48-arm64-apple-darwin.tar.gz
60921b3be448ff2e128be98e63a940c7f5327e10def6b58cf36665cd157967ab  guix-build-818a3c07fb48/output/dist-archive/bitcoin-818a3c07fb48.tar.gz
56f75f7b811da2fc209e41155043e0765938128934964535c12c0b2992cf3484  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/SHA256SUMS.part
fc9afedb71bc5a1bde7cf08ed937dc68cca76faadf17f654e8d0b0d276070909  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/bitcoin-818a3c07fb48-powerpc64-linux-gnu-debug.tar.gz
6a67d618819bf8a78785d4f795b25bc37f756ff1f859d8f06b505422452f6b4e  guix-build-818a3c07fb48/output/powerpc64-linux-gnu/bitcoin-818a3c07fb48-powerpc64-linux-gnu.tar.gz
7b09ea93f4778eb81d1b29d3c26b08f1c9c5de4fb4453536651bf1c2ece1c66b  guix-build-818a3c07fb48/output/riscv64-linux-gnu/SHA256SUMS.part
118c1fc1cc5973d623ca0a4d96973b5c4e8f0d2dc1354b09d5244ec2df01f236  guix-build-818a3c07fb48/output/riscv64-linux-gnu/bitcoin-818a3c07fb48-riscv64-linux-gnu-debug.tar.gz
9d2794fb6f00517ba3ab279e50ecd42d9e25dd4fd5e61b5f8fb31fc81e9c5931  guix-build-818a3c07fb48/output/riscv64-linux-gnu/bitcoin-818a3c07fb48-riscv64-linux-gnu.tar.gz
d6d9910d4c76b553c69d55418b0f577937beef60b4952e241e7a389df5918dc9  guix-build-818a3c07fb48/output/x86_64-apple-darwin/SHA256SUMS.part
8b7409b6c3eaf5425b58055830c506c96a60b96a658df7b41f08ccd4d2cfe7ef  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin-unsigned.tar.gz
86443fa7f87c38ec127ac88abe73fc9bcc8ae17adc87345daf930509ebe22f3a  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin-unsigned.zip
ffcf5040db9c5b182df7b84dc41fba79231d1274b7759b87cd72f680b1c3340a  guix-build-818a3c07fb48/output/x86_64-apple-darwin/bitcoin-818a3c07fb48-x86_64-apple-darwin.tar.gz
54292290975c5ff1028784dfce5fc4726a94c260665051fe65c4c521e8d0247a  guix-build-818a3c07fb48/output/x86_64-linux-gnu/SHA256SUMS.part
a28cd6961446b3302d6a1410a14f597f81839116d09b169709e00f9d783d430f  guix-build-818a3c07fb48/output/x86_64-linux-gnu/bitcoin-818a3c07fb48-x86_64-linux-gnu-debug.tar.gz
cf46aae7ce6d959111bd8516093a9bd6aa3a11f0c1c8ae33a9de6bbb0767d333  guix-build-818a3c07fb48/output/x86_64-linux-gnu/bitcoin-818a3c07fb48-x86_64-linux-gnu.tar.gz
e6a780c7e9124b2b3423cdefa7ed6630f7fbf70a381e53d606580a9cca8a9f05  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/SHA256SUMS.part
d88527ec42dd21ba366148b926205d01ad06fcc2e44796c05f9cda53a7b7a3ad  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-debug.zip
0b6dec24b248b3e5b45188554842b24d5341a1321608087a6adaea16c7228e3e  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-setup-unsigned.exe
a0779f90be6a3b2e252c167892ce94158b47474e150565f3ea83862f7fc58862  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64-unsigned.tar.gz
310d3e0d46a72d6040ff80712c65cb39c4cbbafd714ae69a6e12f9502b0b6853  guix-build-818a3c07fb48/output/x86_64-w64-mingw32/bitcoin-818a3c07fb48-win64.zip
```

**Pull request closed without merging**
