### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/tree/cmake-staging) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/9e1306fc886bcf8024ec37687bbfb8ae364286d6) one with the squashed "!fixup" commits.

Steps to reproduce:
1. Apply the `git rebase -i --autosquash 9e1306fc886bcf8024ec37687bbfb8ae364286d6` command (there is a conflict, which can be resolved by removing the `.github/workflows/ci.yml` file).
2. Backport changes from the following PRs:
- https://github.com/bitcoin/bitcoin/pull/26684
- https://github.com/bitcoin/bitcoin/pull/28051
- https://github.com/bitcoin/bitcoin/pull/28075

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @vasild @TheCharlatan @theuni @pablomartin4btc @m3dwards :)

**Comment by hebasto** [comment]
CI looks green :)

The plan is to process https://github.com/hebasto/bitcoin/pull/72 after approving this PR.

**Review by TheCharlatan — APPROVED** [review]
ACK 67ceebba310899f553c6f9f94f21bf86c9bde2d7

**Comment by hebasto** [comment]
@TheCharlatan 

Thank you for your review!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Comment by pablomartin4btc** [comment]
post-merge ACK 67ceebba310899f553c6f9f94f21bf86c9bde2d7/ I was in the middle of it when the PR got closed.

Reproduced the steps detailed in the [description](https://github.com/hebasto/bitcoin/pull/75#issue-2072510578).

**Review by pablomartin4btc — COMMENTED** [review]
post-merge ACK 67ceebba310899f553c6f9f94f21bf86c9bde2d7/ I was in the middle of it when the PR got closed.

Reproduced the steps detailed in the [description](https://github.com/hebasto/bitcoin/pull/75#issue-2072510578).

**Pull request closed without merging**
