### PR TITLE
cmake: Bump CMake minimum required version up to 3.22

### PR DESCRIPTION
**Pull request by hebasto**
Considering the time when the new CMake-based build system will be available for users and https://github.com/bitcoin/bitcoin/pull/29091, it seems reasonable to drop support for CMake versions older than 3.22.

For CMake version availability, please refer to https://repology.org/project/cmake/versions.

If an OS has no supported CMake in its system/default package manager, the user is still able to download it from https://cmake.org/download//

Please refer to commit messages for detailed explanations of code changes.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Concept ACK :)

**Comment by TheCharlatan** [comment]
Guix build:
```
80c9a64895c7419056a00867a75dfe8c262d00ea78858044084d8cbd4948fde8  guix-build-a6a746e5b390/output/aarch64-linux-gnu/SHA256SUMS.part
fbfc91cfc5bd625441d69cc44054cf6e5aa4f307820f1c7b27e31e032461c674  guix-build-a6a746e5b390/output/aarch64-linux-gnu/bitcoin-a6a746e5b390-aarch64-linux-gnu-debug.tar.gz
7b196fda321bc35fc4cf2b6e36e53800e5b0826864bcda2001ef2e5d3330ba5f  guix-build-a6a746e5b390/output/aarch64-linux-gnu/bitcoin-a6a746e5b390-aarch64-linux-gnu.tar.gz
bc148454bd90aad9d1416b326e0f16b4b9ec71a76ca64c64f640d6b9ac319528  guix-build-a6a746e5b390/output/arm-linux-gnueabihf/SHA256SUMS.part
054de54f1473974b0fb2247c2b2199891b0b294ee6e3e7a6c3553ef0df663721  guix-build-a6a746e5b390/output/arm-linux-gnueabihf/bitcoin-a6a746e5b390-arm-linux-gnueabihf-debug.tar.gz
c98bac18196e267d46b5d7f7f73fc4d0f38861597ec526dd0599819a80f48e4f  guix-build-a6a746e5b390/output/arm-linux-gnueabihf/bitcoin-a6a746e5b390-arm-linux-gnueabihf.tar.gz
47e42797b4eea1fb30a376926c55cfd8b9b1a1aa434a7c078448992dc632c669  guix-build-a6a746e5b390/output/dist-archive/bitcoin-a6a746e5b390.tar.gz
a69c9cbf6a128117106cb430ffa6f97addd2b63475389c8ff24af2087f8913d1  guix-build-a6a746e5b390/output/powerpc64-linux-gnu/SHA256SUMS.part
8d5f3e7873bf2db504cf83b3f09bdcb69b54a5177b1ac8f65e52153490d4010b  guix-build-a6a746e5b390/output/powerpc64-linux-gnu/bitcoin-a6a746e5b390-powerpc64-linux-gnu-debug.tar.gz
940061cf357d165317bb4ed77060c3c14203e34e606ac160d97da5c4dee5b5ec  guix-build-a6a746e5b390/output/powerpc64-linux-gnu/bitcoin-a6a746e5b390-powerpc64-linux-gnu.tar.gz
5b7d1b8cb916dbe7b890df3acf2992ed2a4f8ee7b47a4bd0d06632579c2cbc72  guix-build-a6a746e5b390/output/powerpc64le-linux-gnu/SHA256SUMS.part
f277eb0e49bf0e69e31e0bd66fe348c11bfe2d014f2bb3beccf101cde515e58c  guix-build-a6a746e5b390/output/powerpc64le-linux-gnu/bitcoin-a6a746e5b390-powerpc64le-linux-gnu-debug.tar.gz
6f0b8c2257c9629035de2e0d2ca05f8e93b5a0f8057fc5cb63fb76f74e472b1a  guix-build-a6a746e5b390/output/powerpc64le-linux-gnu/bitcoin-a6a746e5b390-powerpc64le-linux-gnu.tar.gz
ab4caed3d7a8a427ba40ea9c5918bfe0b690d78f63976fa005b0919be4cc4344  guix-build-a6a746e5b390/output/riscv64-linux-gnu/SHA256SUMS.part
675f2272de755293327c0b67c1f64f2adcfcfda9f8a56e5526aabd0cbb40841b  guix-build-a6a746e5b390/output/riscv64-linux-gnu/bitcoin-a6a746e5b390-riscv64-linux-gnu-debug.tar.gz
8db14a0d6ff90a718275531699fba1b52e412f3a0fb9391ba1f804cf78a22cce  guix-build-a6a746e5b390/output/riscv64-linux-gnu/bitcoin-a6a746e5b390-riscv64-linux-gnu.tar.gz
affe152e26ce4852ac8d4bdb2c2b7cde08faa0319fc829bb703249584097f340  guix-build-a6a746e5b390/output/x86_64-linux-gnu/SHA256SUMS.part
711d838d98a421a73bf55d34d0a52004735565cb67c77f93b32ff21ac9b53c07  guix-build-a6a746e5b390/output/x86_64-linux-gnu/bitcoin-a6a746e5b390-x86_64-linux-gnu-debug.tar.gz
4cfa08385708db5f3f9ab4b785ffdf8f797e240a0a838de905e8d161ea0794af  guix-build-a6a746e5b390/output/x86_64-linux-gnu/bitcoin-a6a746e5b390-x86_64-linux-gnu.tar.gz
5cb19c90af886c735c7ef11f4fdaa4dff0b5986c2d0ac6a4742597478433bca9  guix-build-a6a746e5b390/output/x86_64-w64-mingw32/SHA256SUMS.part
962ac2fe8aceee9eb349c95ee3fec078101531fbd924d0a009da41ed097c9620  guix-build-a6a746e5b390/output/x86_64-w64-mingw32/bitcoin-a6a746e5b390-win64-debug.zip
5f8b0de0b8d482d6125686621d4f074ac968f1ac3bbb78ef37b89f607ec58f32  guix-build-a6a746e5b390/output/x86_64-w64-mingw32/bitcoin-a6a746e5b390-win64-setup-unsigned.exe
0756fbeea0791408a4eeeb182cd32023fecc8a36694b6ff2c23a7c8478755072  guix-build-a6a746e5b390/output/x86_64-w64-mingw32/bitcoin-a6a746e5b390-win64-unsigned.tar.gz
68c17f0a9c725fb4dbcaa62d04950cbe49c3c255c5bc9bb0bec3251485f180d4  guix-build-a6a746e5b390/output/x86_64-w64-mingw32/bitcoin-a6a746e5b390-win64.zip
```

**Review by pablomartin4btc — COMMENTED** [review]
Concept ACK

I'll perform a cross-build later today, especially due to the removal of the workaround on commit ae5bd32039a3cbdf6095600831bfe653a7ba69cd (`cmake/module/CrossPkgConfig.cmake`) not being necessary anymore (even CIs indicate to work fine).

**Review by pablomartin4btc — APPROVED** [review]
tACK a6a746e5b390b2d5b78c3ab6848af686f0664bad

Cross-building for Windows on Ubuntu 22.04 & Ubuntu 22.04 on WSL.

Ran successfully `ctest `and `test_bitcoin-qt` on both WSL and Windows 11 Pro.

**Comment by fanquake** [comment]
ACK on bumping the version. I haven't yet looked at the all the cleanups.

**Review by vasild — APPROVED** [review]
ACK a6a746e5b390b2d5b78c3ab6848af686f0664bad

+31 / -100 :heart:

**Pull request merged**
