### PR TITLE
cmake: Drop unused packages from Guix manifest

### PR DESCRIPTION
**Pull request by hebasto**
Autotools installation is not required at this moment.

~Drafted because of this~ [feedback](https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1699904124):
> Autotools might not be used currently for sqlite (libtool still is), but we can't rule out entirely that it wont be used going forward. For example, if we need to regenerate the configure script for some reason. This has happened in the past, for example, something like [6897c4b](https://github.com/bitcoin/bitcoin/commit/6897c4bdf51a4aa74320ebfffa9467db14670109). This might be very unlikely here, but not impossible.
> 
> Note that this would also breakdown, if we were to shift to building from source (requiring us to generate the build scripts oursevles), rather than using the tarballs with everything pre-generated (and unverifiable/opauge). (In this case it'd also be all of the Linux GUI packages that'd require it).

My Guix build:
```
x86_64
b21ad69710ffc70dac55c40fdb3287cdb50286aa434a590f2eb9eae943c2c1e6  guix-build-adee830febcf/output/aarch64-linux-gnu/SHA256SUMS.part
597a4c00582ea8be1eadfec43880fac7cb56b1df3257e3439b2eeb7fc4c33da2  guix-build-adee830febcf/output/aarch64-linux-gnu/bitcoin-adee830febcf-aarch64-linux-gnu-debug.tar.gz
8af7d4c70b6bcb69705e9124b0f19959e2a4c6eccffec9a97ad0a9e24ffc9cf1  guix-build-adee830febcf/output/aarch64-linux-gnu/bitcoin-adee830febcf-aarch64-linux-gnu.tar.gz
3289c81b14b1b44f1208b1297692ad4ba23c2e65aed43def95d6b6fc9937cc7c  guix-build-adee830febcf/output/arm-linux-gnueabihf/SHA256SUMS.part
1240e0a7b61352b8f532fb113653258266ac9ef3687b9e0920ab261c3702d7d6  guix-build-adee830febcf/output/arm-linux-gnueabihf/bitcoin-adee830febcf-arm-linux-gnueabihf-debug.tar.gz
25b118ddd8d5bbe54f56b259f48eba76fd62a5cee17f074972c33409480ffc91  guix-build-adee830febcf/output/arm-linux-gnueabihf/bitcoin-adee830febcf-arm-linux-gnueabihf.tar.gz
48c985c03352b5e5d7581bd9283321f4f9681e241b4c55ed6109ad2cb9fec738  guix-build-adee830febcf/output/arm64-apple-darwin/SHA256SUMS.part
4d6d1092b8208b5e0ff3af7bad1fa858eb9b52ff3acb091e876b6b509306d01f  guix-build-adee830febcf/output/arm64-apple-darwin/bitcoin-adee830febcf-arm64-apple-darwin-unsigned.tar.gz
8a7a69de4058c143190128867d7ff1a490035ec384f4dd913da799a8f15c62d3  guix-build-adee830febcf/output/arm64-apple-darwin/bitcoin-adee830febcf-arm64-apple-darwin-unsigned.zip
b949eccdb836537eae14486891d22769d8968b25da8921acc4f6873549380940  guix-build-adee830febcf/output/arm64-apple-darwin/bitcoin-adee830febcf-arm64-apple-darwin.tar.gz
0f86e37acc22ab04513f0e01e080ed48184c13e85577c0e523decf20aa8d1da5  guix-build-adee830febcf/output/dist-archive/bitcoin-adee830febcf.tar.gz
08060a7654c545b06bd8f00e0187dd0d57a7de335517b808d68f426191f5555e  guix-build-adee830febcf/output/powerpc64-linux-gnu/SHA256SUMS.part
c4fe227333a4bdeb05764b5fab04f0767c816b05e2217d92eba79b43048b8c65  guix-build-adee830febcf/output/powerpc64-linux-gnu/bitcoin-adee830febcf-powerpc64-linux-gnu-debug.tar.gz
4e724bcfd1f3f7aef93f8ea041cc92f5be0046980014dcefbbcb0af4c381508f  guix-build-adee830febcf/output/powerpc64-linux-gnu/bitcoin-adee830febcf-powerpc64-linux-gnu.tar.gz
fe2e0e81eb5b826c4e3bd6d1850a97c7330f499418c48498111c36e4df1fef13  guix-build-adee830febcf/output/riscv64-linux-gnu/SHA256SUMS.part
3d80dd507d41e1e98dad9f052dd5c52fe964dd141263a697e73e0498875eabb5  guix-build-adee830febcf/output/riscv64-linux-gnu/bitcoin-adee830febcf-riscv64-linux-gnu-debug.tar.gz
198f0e673ad26c62a1f8e2bdd805c8b045e0f0192f70f3895b3c4309782bd766  guix-build-adee830febcf/output/riscv64-linux-gnu/bitcoin-adee830febcf-riscv64-linux-gnu.tar.gz
3562bf0b37a1cca3034aaaa0a94e615d8dd673a231f3d21a01bee0e1c514eaaf  guix-build-adee830febcf/output/x86_64-apple-darwin/SHA256SUMS.part
4c4b44bb84de29aa8f86820905858d716233dcc4367ba808802ff60eae7892d0  guix-build-adee830febcf/output/x86_64-apple-darwin/bitcoin-adee830febcf-x86_64-apple-darwin-unsigned.tar.gz
3023370ed8950ab520df7dcfaa729007a1e02f69e79aa253b89baa6598ccc33b  guix-build-adee830febcf/output/x86_64-apple-darwin/bitcoin-adee830febcf-x86_64-apple-darwin-unsigned.zip
cdb7e48d90a45fd1517bcb96c9e503db0c616f474e7c2c7da16ead9788982f6d  guix-build-adee830febcf/output/x86_64-apple-darwin/bitcoin-adee830febcf-x86_64-apple-darwin.tar.gz
28e01eb9f129134211993d814fe6bbc1a856306dabb5c6271456062e42ce83e6  guix-build-adee830febcf/output/x86_64-linux-gnu/SHA256SUMS.part
4e7c5f359a2d15250783bd1dfa975812d63ba6600be7778569920ed07c99c1cd  guix-build-adee830febcf/output/x86_64-linux-gnu/bitcoin-adee830febcf-x86_64-linux-gnu-debug.tar.gz
7ff4823e63cfb0284857c4a24ca80b38bf12dd919d8201ee1a6d0bf70fe5bd0f  guix-build-adee830febcf/output/x86_64-linux-gnu/bitcoin-adee830febcf-x86_64-linux-gnu.tar.gz
8ef0174520bf5a47d61b6a3bf6b7e684939ab76901e2235affe8df509b3d835c  guix-build-adee830febcf/output/x86_64-w64-mingw32/SHA256SUMS.part
f145a5d7c1c0953a569e038d2d3a21d93a9abad48f4c36289893dacc67498bcc  guix-build-adee830febcf/output/x86_64-w64-mingw32/bitcoin-adee830febcf-win64-debug.zip
471d0b2724875c8c27c5197824a5eae382b052343f840727bfc2eb9c30873aa5  guix-build-adee830febcf/output/x86_64-w64-mingw32/bitcoin-adee830febcf-win64-setup-unsigned.exe
56a68aa63440bfcb6780ac536f4287eb4a56ffa868d3b27659970e0bd5a9efcd  guix-build-adee830febcf/output/x86_64-w64-mingw32/bitcoin-adee830febcf-win64-unsigned.tar.gz
b1bdf52ae1c0426379065c180c412b0ff569e8bd8fadaa597fd95a54414e9c3d  guix-build-adee830febcf/output/x86_64-w64-mingw32/bitcoin-adee830febcf-win64.zip
```

### CODE REVIEW

**Comment by hebasto** [comment]
Rebased.

**Review by pablomartin4btc — COMMENTED** [review]
ACK 5bd79c8a3b1d2fe2b5592ae64699786d2e117f10

Guix build:
```

97b53eb6575fcead1e7c5a6cd4328b3f273111565d93a731dd27232e893a0ba5  bitcoin-5bd79c8a3b1d-aarch64-linux-gnu-debug.tar.gz
005be1117d9cda160c6237055673537bc31ec703990911728e9a1db9308bd39c  bitcoin-5bd79c8a3b1d-aarch64-linux-gnu.tar.gz
bc253c2b614551f754316fa60a84e18130d25fed712503b68de65ea1e9c5ff01  bitcoin-5bd79c8a3b1d-arm-linux-gnueabihf-debug.tar.gz
36ec70f3c45344e34519ff26498f617af7e49ce6a24c169ae57ad05fa62a5558  bitcoin-5bd79c8a3b1d-arm-linux-gnueabihf.tar.gz
3bb7cd7fd1b8d31226c5cad2d0f5b4b58e75a0875d9e2b81d08dcd3837fd67f8  bitcoin-5bd79c8a3b1d-arm64-apple-darwin-unsigned.tar.gz
e4da873203189a6b0b0c866bda0408a975ee584c49f7fa2b1aca6b82ae5ad3e3  bitcoin-5bd79c8a3b1d-arm64-apple-darwin-unsigned.zip
ba9760a2dece2e77375838b5b55f4dbe9dcf9c01244305447f7272a9667166cf  bitcoin-5bd79c8a3b1d-arm64-apple-darwin.tar.gz
abd20cde611c7a694d48ad4d43b96710899e0ca9bb18855f2df7938127c25c32  bitcoin-5bd79c8a3b1d.tar.gz
2fba9b628254922443fb8c42c83884642b6246e3ae2f4f52ef33458d0aae7013  bitcoin-5bd79c8a3b1d-powerpc64-linux-gnu-debug.tar.gz
5c7e3fdd12aff1e31c0ac4d36001997e7be3d38c0caf910ea26dfb6ec848c8d4  bitcoin-5bd79c8a3b1d-powerpc64-linux-gnu.tar.gz
ad3ae05fbb3cf65fe25a3c9900e3af061f46206523f4f5348b63d4bfd09262cc  bitcoin-5bd79c8a3b1d-riscv64-linux-gnu-debug.tar.gz
5734943ce2d9c623eb7ac28881518af7f175ef0bff43462033cacb86b5d4797a  bitcoin-5bd79c8a3b1d-riscv64-linux-gnu.tar.gz
b30b2d770cd6b17aa0522ed74f2aefb835d75834afac8b430e24bb255bb908cc  bitcoin-5bd79c8a3b1d-x86_64-apple-darwin-unsigned.tar.gz
382b075335442b00be51bd6f82f687fe69e0205d140ccc7c64a40e0d562d44ec  bitcoin-5bd79c8a3b1d-x86_64-apple-darwin-unsigned.zip
9d8c38d419a0390701e164396663227e1174c7d1c02110c1c493875baf1a6e5f  bitcoin-5bd79c8a3b1d-x86_64-apple-darwin.tar.gz
0667ff88b606d7c546860b33c1b05283e94c26de7462d2aedce3370be87d9c55  bitcoin-5bd79c8a3b1d-x86_64-linux-gnu-debug.tar.gz
97b491210a93cd1f56965e348486ef8537f4340a1a3dc3be0e327c4e526ce133  bitcoin-5bd79c8a3b1d-x86_64-linux-gnu.tar.gz
37fa0d5eb76317326caff141e06e9c6cdec6ea6a599748f5d7ed3653e3059231  bitcoin-5bd79c8a3b1d-win64-debug.zip
e8da6957144f6d52e3778bf1fca7949e1271a044de80cf6c2ef89aa9160f78e5  bitcoin-5bd79c8a3b1d-win64-setup-unsigned.exe
55ecfc3f523910a48ed3dc33d56b03254828476f9542dac9d8116033d47c5431  bitcoin-5bd79c8a3b1d-win64-unsigned.tar.gz
ea39931b2cb134113bee325c2adc0ed61a901a0b3fddc89a8a728e03f0251afe  bitcoin-5bd79c8a3b1d-win64.zip
```

**Review by theuni — COMMENTED** [review]
Concept ACK.

I'll defer to @fanquake on this one. Seems we could always add them back if needed, though it'd be nice if things just worked if we ever needed to bootstrap a dep, without having to track down this history.

**Comment by fanquake** [comment]
> I'll defer to @fanquake on this one.

I'm not too fussed at this point. They may just end up back if we do more from-source builds.

**Comment by hebasto** [comment]
Rebased.

**Comment by fanquake** [comment]
I think this can just be rolled into https://github.com/bitcoin/bitcoin/pull/30664.

**Comment by hebasto** [comment]
> I think guix was already bumped to cmake, so this can be done in a separate pull already today?

Done in https://github.com/bitcoin/bitcoin/pull/30752.

**Pull request closed without merging**
