### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/commit/38f75be6e8205aae7cdddfd2d524c63e67186353) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/fa0b5d68823b69f4861b002bbfac2fd36ed46356) one, which includes the main build system changes, with the squashed "!fixup" commits.

Steps to reproduce:
1. Run the command as follows:
```
git checkout 38f75be6e8205aae7cdddfd2d524c63e67186353
git rebase -i --autosquash fa0b5d68823b69f4861b002bbfac2fd36ed46356
```
There are a few conflicts that have to be resolved.

2. Port build system changes from:
- https://github.com/bitcoin/bitcoin/pull/28263
- https://github.com/bitcoin/bitcoin/pull/28923

3. Squash and reorder commits to make their history suitable for a PR to the main repository (it must be a zero-diff change).

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @TheCharlatan @m3dwards :)

**Comment by m3dwards** [comment]
Guix build

```shell
5cef021ba00f903d7633096663febd72853c4584499b8f25ae42ae6dc36f82cf  guix-build-dc490dae00d6/output/aarch64-linux-gnu/SHA256SUMS.part
9cdb2e684b2e0a70c25ec632c1ba346550ee620da8018022e69d455536a4615c  guix-build-dc490dae00d6/output/aarch64-linux-gnu/bitcoin-dc490dae00d6-aarch64-linux-gnu-debug.tar.gz
4da2aed25f0348fb4ebe1b2af01b2a5ce45ddb696c4654d83206e526eb59f02f  guix-build-dc490dae00d6/output/aarch64-linux-gnu/bitcoin-dc490dae00d6-aarch64-linux-gnu.tar.gz
9f5da3540c02dce6f46908a09b91a1e83ddf65e96e21b900f9eaf3d5c63925b6  guix-build-dc490dae00d6/output/arm-linux-gnueabihf/SHA256SUMS.part
17c4ea025c1fade50345056ae1bdb9f84f7a0f229b10131844131ced253a3101  guix-build-dc490dae00d6/output/arm-linux-gnueabihf/bitcoin-dc490dae00d6-arm-linux-gnueabihf-debug.tar.gz
b2336f5405d5a7b8628f0e9d1b37a4f5e113de06e900fa6cd31f38a979aeeb3d  guix-build-dc490dae00d6/output/arm-linux-gnueabihf/bitcoin-dc490dae00d6-arm-linux-gnueabihf.tar.gz
51e4ef6ea6395c69aeb68a3645ce106b56b54d3185be0dbc7fb1802cb8c54b57  guix-build-dc490dae00d6/output/arm64-apple-darwin/SHA256SUMS.part
3677aada031d03766b76ccc57731ecf8c6de77323a65027d7e1feff61f832200  guix-build-dc490dae00d6/output/arm64-apple-darwin/bitcoin-dc490dae00d6-arm64-apple-darwin-unsigned.tar.gz
433ea9ef28d33469f8c6e246952515ebe77f02ff9873aa140091063ff30e7aa7  guix-build-dc490dae00d6/output/arm64-apple-darwin/bitcoin-dc490dae00d6-arm64-apple-darwin-unsigned.zip
c3fb9574d14b24ac6c4949d1d30ecdaaccba128cb18a2c963ff6e9d425e61ea1  guix-build-dc490dae00d6/output/arm64-apple-darwin/bitcoin-dc490dae00d6-arm64-apple-darwin.tar.gz
c6057ab3970124cd001c5cd5c0d9a73e7651fcd27e79a47c16aef9f3ad14262c  guix-build-dc490dae00d6/output/dist-archive/bitcoin-dc490dae00d6.tar.gz
f2788e6c4403fa1f8696ba89dccc2f1aa0fe1568a3545585d323bb21b76711ef  guix-build-dc490dae00d6/output/powerpc64-linux-gnu/SHA256SUMS.part
479db9502720ed8c4a3206563525061071bff29f4dbdc802978af94e751be1d7  guix-build-dc490dae00d6/output/powerpc64-linux-gnu/bitcoin-dc490dae00d6-powerpc64-linux-gnu-debug.tar.gz
f939b9a5525ea860b35e238b6599bce1ee6a871ae43cc991f1ffe8fa3bdbf671  guix-build-dc490dae00d6/output/powerpc64-linux-gnu/bitcoin-dc490dae00d6-powerpc64-linux-gnu.tar.gz
8806e3ad997f3fedd42415fff8899eb3ad19eff24848938197345e0c6d695d58  guix-build-dc490dae00d6/output/riscv64-linux-gnu/SHA256SUMS.part
67beb8c24aea5356f93a60dde85d7f5b53ba3899dd2929a29d0af53e9cccc026  guix-build-dc490dae00d6/output/riscv64-linux-gnu/bitcoin-dc490dae00d6-riscv64-linux-gnu-debug.tar.gz
64bab910ce4726da378a29f131d2aef0da5e8867172cfc9b3aa6ce4f8a1f2b3c  guix-build-dc490dae00d6/output/riscv64-linux-gnu/bitcoin-dc490dae00d6-riscv64-linux-gnu.tar.gz
e0b23586b5345097f69938b9f4b647dd0cf4dad57d1268e3f97e547e778547ef  guix-build-dc490dae00d6/output/x86_64-apple-darwin/SHA256SUMS.part
7efc5d886e43693a4fe33492741ab4034fd4c6ac529508eb3412679b423df3e5  guix-build-dc490dae00d6/output/x86_64-apple-darwin/bitcoin-dc490dae00d6-x86_64-apple-darwin-unsigned.tar.gz
9350523c6b4680c91903281c7bb16b26153a8b4f7dc5bda56c59f8d52a01cc0a  guix-build-dc490dae00d6/output/x86_64-apple-darwin/bitcoin-dc490dae00d6-x86_64-apple-darwin-unsigned.zip
3bc7106aceea901d942041c8561fe2fb79072a9ee2c324344d1b7cc36905bda8  guix-build-dc490dae00d6/output/x86_64-apple-darwin/bitcoin-dc490dae00d6-x86_64-apple-darwin.tar.gz
21aa524795a3ae519914729692793b8221f632cffa87670a0a6c698311177d75  guix-build-dc490dae00d6/output/x86_64-linux-gnu/SHA256SUMS.part
f6b46973ecd4d288fc4f5830402a4769de96a08b6729fe437054398bc363d7a4  guix-build-dc490dae00d6/output/x86_64-linux-gnu/bitcoin-dc490dae00d6-x86_64-linux-gnu-debug.tar.gz
9be915b3f65fb902b49d0ae5b2e8a910f883eb3a61a537e2e9fe6dd27e19f8f7  guix-build-dc490dae00d6/output/x86_64-linux-gnu/bitcoin-dc490dae00d6-x86_64-linux-gnu.tar.gz
21f26e55a281e4334771106369d7190406c78d25d0df5f54a6523a41f539d0f6  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/SHA256SUMS.part
a7e8fb83597e22cf503e273117a9b242676da312bfde5832ef926e6b64261a0a  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64-debug.zip
f5ec21360dd9d1dc255f9cadf89a9d48659268256ad3f53fa319b3ecb669c22b  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64-setup-unsigned.exe
fa4aa5de4365887cfc268277353e2c63d219cd3b7e2a24dc26aa7734e692881a  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64-unsigned.tar.gz
90e7f8fd428cdbdd04c6114744abfbfd3b648d6bf19f40d5eade59e270357429  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64.zip
```

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
5cef021ba00f903d7633096663febd72853c4584499b8f25ae42ae6dc36f82cf  guix-build-dc490dae00d6/output/aarch64-linux-gnu/SHA256SUMS.part
9cdb2e684b2e0a70c25ec632c1ba346550ee620da8018022e69d455536a4615c  guix-build-dc490dae00d6/output/aarch64-linux-gnu/bitcoin-dc490dae00d6-aarch64-linux-gnu-debug.tar.gz
4da2aed25f0348fb4ebe1b2af01b2a5ce45ddb696c4654d83206e526eb59f02f  guix-build-dc490dae00d6/output/aarch64-linux-gnu/bitcoin-dc490dae00d6-aarch64-linux-gnu.tar.gz
9f5da3540c02dce6f46908a09b91a1e83ddf65e96e21b900f9eaf3d5c63925b6  guix-build-dc490dae00d6/output/arm-linux-gnueabihf/SHA256SUMS.part
17c4ea025c1fade50345056ae1bdb9f84f7a0f229b10131844131ced253a3101  guix-build-dc490dae00d6/output/arm-linux-gnueabihf/bitcoin-dc490dae00d6-arm-linux-gnueabihf-debug.tar.gz
b2336f5405d5a7b8628f0e9d1b37a4f5e113de06e900fa6cd31f38a979aeeb3d  guix-build-dc490dae00d6/output/arm-linux-gnueabihf/bitcoin-dc490dae00d6-arm-linux-gnueabihf.tar.gz
51e4ef6ea6395c69aeb68a3645ce106b56b54d3185be0dbc7fb1802cb8c54b57  guix-build-dc490dae00d6/output/arm64-apple-darwin/SHA256SUMS.part
3677aada031d03766b76ccc57731ecf8c6de77323a65027d7e1feff61f832200  guix-build-dc490dae00d6/output/arm64-apple-darwin/bitcoin-dc490dae00d6-arm64-apple-darwin-unsigned.tar.gz
433ea9ef28d33469f8c6e246952515ebe77f02ff9873aa140091063ff30e7aa7  guix-build-dc490dae00d6/output/arm64-apple-darwin/bitcoin-dc490dae00d6-arm64-apple-darwin-unsigned.zip
c3fb9574d14b24ac6c4949d1d30ecdaaccba128cb18a2c963ff6e9d425e61ea1  guix-build-dc490dae00d6/output/arm64-apple-darwin/bitcoin-dc490dae00d6-arm64-apple-darwin.tar.gz
c6057ab3970124cd001c5cd5c0d9a73e7651fcd27e79a47c16aef9f3ad14262c  guix-build-dc490dae00d6/output/dist-archive/bitcoin-dc490dae00d6.tar.gz
f2788e6c4403fa1f8696ba89dccc2f1aa0fe1568a3545585d323bb21b76711ef  guix-build-dc490dae00d6/output/powerpc64-linux-gnu/SHA256SUMS.part
479db9502720ed8c4a3206563525061071bff29f4dbdc802978af94e751be1d7  guix-build-dc490dae00d6/output/powerpc64-linux-gnu/bitcoin-dc490dae00d6-powerpc64-linux-gnu-debug.tar.gz
f939b9a5525ea860b35e238b6599bce1ee6a871ae43cc991f1ffe8fa3bdbf671  guix-build-dc490dae00d6/output/powerpc64-linux-gnu/bitcoin-dc490dae00d6-powerpc64-linux-gnu.tar.gz
8806e3ad997f3fedd42415fff8899eb3ad19eff24848938197345e0c6d695d58  guix-build-dc490dae00d6/output/riscv64-linux-gnu/SHA256SUMS.part
67beb8c24aea5356f93a60dde85d7f5b53ba3899dd2929a29d0af53e9cccc026  guix-build-dc490dae00d6/output/riscv64-linux-gnu/bitcoin-dc490dae00d6-riscv64-linux-gnu-debug.tar.gz
64bab910ce4726da378a29f131d2aef0da5e8867172cfc9b3aa6ce4f8a1f2b3c  guix-build-dc490dae00d6/output/riscv64-linux-gnu/bitcoin-dc490dae00d6-riscv64-linux-gnu.tar.gz
e0b23586b5345097f69938b9f4b647dd0cf4dad57d1268e3f97e547e778547ef  guix-build-dc490dae00d6/output/x86_64-apple-darwin/SHA256SUMS.part
7efc5d886e43693a4fe33492741ab4034fd4c6ac529508eb3412679b423df3e5  guix-build-dc490dae00d6/output/x86_64-apple-darwin/bitcoin-dc490dae00d6-x86_64-apple-darwin-unsigned.tar.gz
9350523c6b4680c91903281c7bb16b26153a8b4f7dc5bda56c59f8d52a01cc0a  guix-build-dc490dae00d6/output/x86_64-apple-darwin/bitcoin-dc490dae00d6-x86_64-apple-darwin-unsigned.zip
3bc7106aceea901d942041c8561fe2fb79072a9ee2c324344d1b7cc36905bda8  guix-build-dc490dae00d6/output/x86_64-apple-darwin/bitcoin-dc490dae00d6-x86_64-apple-darwin.tar.gz
21aa524795a3ae519914729692793b8221f632cffa87670a0a6c698311177d75  guix-build-dc490dae00d6/output/x86_64-linux-gnu/SHA256SUMS.part
f6b46973ecd4d288fc4f5830402a4769de96a08b6729fe437054398bc363d7a4  guix-build-dc490dae00d6/output/x86_64-linux-gnu/bitcoin-dc490dae00d6-x86_64-linux-gnu-debug.tar.gz
9be915b3f65fb902b49d0ae5b2e8a910f883eb3a61a537e2e9fe6dd27e19f8f7  guix-build-dc490dae00d6/output/x86_64-linux-gnu/bitcoin-dc490dae00d6-x86_64-linux-gnu.tar.gz
21f26e55a281e4334771106369d7190406c78d25d0df5f54a6523a41f539d0f6  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/SHA256SUMS.part
a7e8fb83597e22cf503e273117a9b242676da312bfde5832ef926e6b64261a0a  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64-debug.zip
f5ec21360dd9d1dc255f9cadf89a9d48659268256ad3f53fa319b3ecb669c22b  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64-setup-unsigned.exe
fa4aa5de4365887cfc268277353e2c63d219cd3b7e2a24dc26aa7734e692881a  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64-unsigned.tar.gz
90e7f8fd428cdbdd04c6114744abfbfd3b648d6bf19f40d5eade59e270357429  guix-build-dc490dae00d6/output/x86_64-w64-mingw32/bitcoin-dc490dae00d6-win64.zip
```

**Comment by hebasto** [comment]
@m3dwards 

Thank you for your review!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Pull request closed without merging**
