### PR TITLE
cmake/module/Maintenance.cmake:deploydir:remove .zip

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
fixes issue when using generator Xcode (probably in other generators as well.

cmake complains that deploy and deploydir share a target.

**Comment by hebasto** [comment]
What is an issue that this PR aims to resolve?

**Comment by RandyMcMillan** [comment]
> fixes issue when using generator Xcode (probably in other generators as well.
> 
> cmake fails and complains that deploy and deploydir share a target.

**Comment by hebasto** [comment]
What are the steps to reproduce the issue?

**Comment by RandyMcMillan** [comment]
thanks for the prompt response...

with build gui option ON
cmake . -B build -G Xcode

Attempting to recreate with screenshots now. :)

**Comment by RandyMcMillan** [comment]
Screenshot 2024-06-30 at 6 13 53 PM

**Comment by RandyMcMillan** [comment]
Screenshot 2024-06-30 at 6 15 16 PM

**Pull request closed without merging**
