### PR TITLE
cmake: Add `WITH_DBUS` configuration option

### PR DESCRIPTION
**Pull request by hebasto**
This PR adds a new `WITH_DBUS` configuration option, which is an analogue of Autotools' `--with-qtdbus`.

### CODE REVIEW

**Comment by fanquake** [comment]
Is this actually something we need (to port) an option for.

**Comment by hebasto** [comment]
> Is this actually something we need (to port) an option for.

cc @laanw

**Comment by hebasto** [comment]
> Is this actually something we need (to port) an option for.

cc @laanwj

**Comment by laanwj** [comment]
> Is this actually something we need (to port) an option for.

i think so. Not all UNIX platforms use DBUS. On Linux it's safe to assume it's there. On MacOS and Windows it's not a thing.

FWIW i tried to get rid of the custom notification stuff a while ago, but Qt's notificator still falls back to ancient X11 notifications which are ignored (or look very shitty) on modern platforms. Maybe qt6 changes this?  i dunno. But for now t's really necessary.

**Comment by theuni** [comment]
Should probably get rid of the `HAVE_CONFIG_H`?

**Comment by hebasto** [comment]
> Should probably get rid of the `HAVE_CONFIG_H` (in qt/notificator.cpp) ?

Sure. Removed.

**Comment by hebasto** [comment]
@theuni 
> Should probably get rid of the `HAVE_CONFIG_H` (in qt/notificator.cpp) ?

FWIW, https://github.com/hebasto/bitcoin/pull/177 removes unsed `HAVE_CONFIG_H` in the entire codebase.

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
Rebased on top of the merged https://github.com/hebasto/bitcoin/pull/173.

**Pull request merged**
