### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/commit/f918ccb8d3711b04e0b8c214846bbedb0f90b8aa) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/eb0bdbdd753bca97120247b921fd29d606fea6e9) one, which includes the main build system changes, with the squashed "!fixup" commits.

Steps to reproduce:
1. Run the command as follows:
```
git checkout f918ccb8d3711b04e0b8c214846bbedb0f90b8aa
git rebase -i --autosquash eb0bdbdd753bca97120247b921fd29d606fea6e9
```
There are a few conflicts that have to be resolved.

2. Squash the _"cmake [FIXUP]: Move `find_program(brew)` out from introspection file"_ commit manually by pulling its changes into the two earlier commits: _"cmake: Add wallet functionality"_ and _"cmake: Build `bitcoin-qt` executable"_.

3. Reorder the recent commits to pop up the docs and CI changes.

4. Port build system changes from https://github.com/bitcoin/bitcoin/pull/29623.

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @m3dwards @vasild @TheCharlatan @pablomartin4btc :)

**Review by TheCharlatan — APPROVED** [review]
lgtm

**Comment by hebasto** [comment]
@TheCharlatan

Thank you for your review!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Comment by hebasto** [comment]
My Guix builds:
```
x86_64
8010c96ab8a8a9cbce200400b35bb84b528334b37803c0f8943d8b3dcf381c13  guix-build-22270eedb0bd/output/aarch64-linux-gnu/SHA256SUMS.part
8f221b4f9cb821ed94d675cdc8d31f1b55c6ade7e714c4e777449df688a1ca5e  guix-build-22270eedb0bd/output/aarch64-linux-gnu/bitcoin-22270eedb0bd-aarch64-linux-gnu-debug.tar.gz
aa229b0fc69ba41f10a2d47cb4233fbe3c7f930058a5cfdd28ecb37efabb1287  guix-build-22270eedb0bd/output/aarch64-linux-gnu/bitcoin-22270eedb0bd-aarch64-linux-gnu.tar.gz
c1a48c413bed28c7727f5b7c758c91b9142b1cf013e6f250970c8dbcb0987a79  guix-build-22270eedb0bd/output/arm-linux-gnueabihf/SHA256SUMS.part
084a7d64b611f33315b4bb8fca744e9de651d4ab507489216e6b684dadcca868  guix-build-22270eedb0bd/output/arm-linux-gnueabihf/bitcoin-22270eedb0bd-arm-linux-gnueabihf-debug.tar.gz
61322058e9eb38c1345e96d389a43f672d0edb09b8ec2ee246ae9fd7f291235b  guix-build-22270eedb0bd/output/arm-linux-gnueabihf/bitcoin-22270eedb0bd-arm-linux-gnueabihf.tar.gz
065cf0e54da424d34e4708b1f4c9751d8848170fcee12f23014ec84782597f12  guix-build-22270eedb0bd/output/arm64-apple-darwin/SHA256SUMS.part
51388e56b527641d5ab783744b363174a17528a5dc22205b4a185885fd754a63  guix-build-22270eedb0bd/output/arm64-apple-darwin/bitcoin-22270eedb0bd-arm64-apple-darwin-unsigned.tar.gz
799c8591049075854101a2f3545b558c2b83d4b9f680d54d174e00b7d5f78dc7  guix-build-22270eedb0bd/output/arm64-apple-darwin/bitcoin-22270eedb0bd-arm64-apple-darwin-unsigned.zip
fd39ff5fdfae0895f96a9a9141f16615ea92c32aee175216e638453b1cae5176  guix-build-22270eedb0bd/output/arm64-apple-darwin/bitcoin-22270eedb0bd-arm64-apple-darwin.tar.gz
ff373484abc6784f6c73fe4f8c2ff33aadb11d00bfe51060d1daf70da77cf4cb  guix-build-22270eedb0bd/output/dist-archive/bitcoin-22270eedb0bd.tar.gz
fdd0f8d3f32df54236921104c173ec94c611f188dc56860f0fbe35ff8d1f0678  guix-build-22270eedb0bd/output/powerpc64-linux-gnu/SHA256SUMS.part
dc9eabea899fd8161f8df398d8a995c60e9166814c8226f4a72d63c7f1abcf71  guix-build-22270eedb0bd/output/powerpc64-linux-gnu/bitcoin-22270eedb0bd-powerpc64-linux-gnu-debug.tar.gz
40c3378bdbde96946d4602844f58d85b45de64aee3ac8a3b12dc6a3bcaae25a1  guix-build-22270eedb0bd/output/powerpc64-linux-gnu/bitcoin-22270eedb0bd-powerpc64-linux-gnu.tar.gz
91c7cb48c3861857cf114fdf90acb9740eb68d9b0fc57765092924a11996fb2f  guix-build-22270eedb0bd/output/riscv64-linux-gnu/SHA256SUMS.part
009d07a1ebcda9ad84e70e39e67f53fb6ef4364d2b401e17b51e83e54a1f9fd5  guix-build-22270eedb0bd/output/riscv64-linux-gnu/bitcoin-22270eedb0bd-riscv64-linux-gnu-debug.tar.gz
a13f7547c22779e7580f07d229a99b2ab0600ddea28eb6a82f4bc6b8df5e3b13  guix-build-22270eedb0bd/output/riscv64-linux-gnu/bitcoin-22270eedb0bd-riscv64-linux-gnu.tar.gz
4ffe7e0a3c9d4789cbca014226839c54b3d875403d522064793ec068b1604b95  guix-build-22270eedb0bd/output/x86_64-apple-darwin/SHA256SUMS.part
b9a93ea6a53229ba4b133b86bd61a5a6f181d93ac0de2d5961aec7b4d8957f6f  guix-build-22270eedb0bd/output/x86_64-apple-darwin/bitcoin-22270eedb0bd-x86_64-apple-darwin-unsigned.tar.gz
496df2cff86a0eb47c4ea8a3bb482dda7ae28d601295517d2dd225c978a08769  guix-build-22270eedb0bd/output/x86_64-apple-darwin/bitcoin-22270eedb0bd-x86_64-apple-darwin-unsigned.zip
635d5ba5555bca647d5dcedf86f39687c706a66f13c5e9b88a7a435951a56180  guix-build-22270eedb0bd/output/x86_64-apple-darwin/bitcoin-22270eedb0bd-x86_64-apple-darwin.tar.gz
c70693564fc78147df9a152faaf4f8a7bee8764af9fb02c2687ccdd4c95a3646  guix-build-22270eedb0bd/output/x86_64-linux-gnu/SHA256SUMS.part
4838f5d77364a7296e9f4fb52905a2a06c93fd15a0ba6d91a79578ba60d4ede0  guix-build-22270eedb0bd/output/x86_64-linux-gnu/bitcoin-22270eedb0bd-x86_64-linux-gnu-debug.tar.gz
996b54b23d9615efa610b69a9b0f09c35a1e1bae5631f7b4cb313c08b4463fda  guix-build-22270eedb0bd/output/x86_64-linux-gnu/bitcoin-22270eedb0bd-x86_64-linux-gnu.tar.gz
ca312a26cfd831636278da363bf922f0fb58fd697e5fec0020f0add1478eeb2a  guix-build-22270eedb0bd/output/x86_64-w64-mingw32/SHA256SUMS.part
8c9ff7b8e378b1b8168c747cc8d11455cba5fdeaecb30686ba7dbe3b8fb061bf  guix-build-22270eedb0bd/output/x86_64-w64-mingw32/bitcoin-22270eedb0bd-win64-debug.zip
d8aa0e11694f6c6e9842ec12889c2649c677ff86842882210b127638878d10f7  guix-build-22270eedb0bd/output/x86_64-w64-mingw32/bitcoin-22270eedb0bd-win64-setup-unsigned.exe
1ba1e8dc14bf6ed1c7d9a0f96837e573a8999f629b5086f251a36c5d7cddaa58  guix-build-22270eedb0bd/output/x86_64-w64-mingw32/bitcoin-22270eedb0bd-win64-unsigned.tar.gz
6cc9acbe14755a1e2f7ec697eee6d3129e31fb0548ef42d9db886d7df527c1dd  guix-build-22270eedb0bd/output/x86_64-w64-mingw32/bitcoin-22270eedb0bd-win64.zip
```

**Pull request closed without merging**
