### PR TITLE
Rebased cmake-staging branch (post PRs 33, 37)

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/tree/cmake-staging) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/43704827b4c9c178f3651a005e26c09103cd4189) one with the squashed "!fixup" commits.

Testing instructions are the same as for https://github.com/hebasto/bitcoin/pull/31:
- https://github.com/hebasto/bitcoin/pull/31#issue-1899572326
- https://github.com/hebasto/bitcoin/pull/31#issuecomment-1722338779 (except for Debian 10 with CMake 3.13)

---

A note for reviewers:

First, the `git rebase -i --autosquash master` command was applied:
[cmake-staging/pr38-init](https://github.com/hebasto/bitcoin/tree/cmake-staging/pr38-init) -- > [cmake-staging/pr38-autosquash](https://github.com/hebasto/bitcoin/tree/cmake-staging/pr38-autosquash)

Then, the recent changes in the build system in the master branch were applied:
[cmake-staging/pr38-autosquash](https://github.com/hebasto/bitcoin/tree/cmake-staging/pr38-autosquash) --> this PR branch

### CODE REVIEW

**Comment by hebasto** [comment]
Many thanks to @TheCharlatan who suggested to leverage the "fixup/autosquash" git functionality!

**Comment by theuni** [comment]
For whatever reason, I had to move the "[fixup! cmake: Add position independent code support](https://github.com/hebasto/bitcoin/commit/1246971e3d521e011ad06fbf20faecbed3d8ad15)" down to after the "add bitcoind" commit in order for the rebase to work. Maybe some config option difference for handling merge order or something?

After that, following along, the diff from this PR to what I generated with my rebase:
```diff
 $ git diff HEAD..hebasto/231024-linear
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6a5e9dcc66..10b484bebd 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,7 +18,7 @@
 cmake_minimum_required(VERSION 3.16...3.28)

 project("Bitcoin Core"
-  VERSION 25.99.0
+  VERSION 26.99.0
   DESCRIPTION "Bitcoin client software"
   HOMEPAGE_URL "https://bitcoincore.org/"
   LANGUAGES CXX ASM
@@ -232,7 +232,7 @@ endif()

 include(cmake/optional.cmake)

-find_package(Python3 3.8 COMPONENTS Interpreter)
+find_package(Python3 3.9 COMPONENTS Interpreter)
 set(PYTHON_COMMAND ${Python3_EXECUTABLE})

 add_subdirectory(src)
diff --git a/src/bench/CMakeLists.txt b/src/bench/CMakeLists.txt
index feec7290b1..3e9b144c77 100644
--- a/src/bench/CMakeLists.txt
+++ b/src/bench/CMakeLists.txt
@@ -23,6 +23,7 @@ add_executable(bench_bitcoin
   checkqueue.cpp
   crypto_hash.cpp
   descriptors.cpp
+  disconnected_transactions.cpp
   duplicate_inputs.cpp
   ellswift.cpp
   examples.cpp
```

The version bump is obvious.
The python bump is from: https://github.com/bitcoin/bitcoin/pull/28211
The additional cpp is from: https://github.com/bitcoin/bitcoin/pull/28385

**Comment by theuni** [comment]
`-fstack-reuse=none` is the other thing that I can think of that would need to be addressed in a recent buildsystem rebase, but those options come in #32.

LGTM. I'm curious if other reviewers have the same issue reproducing the rebase?

**Comment by vasild** [comment]
LGTM

I got the same experience as in https://github.com/hebasto/bitcoin/pull/38#issuecomment-1780042733 and produced the same diff.

The change from commit 1246971e3d `fixup! cmake: Add position independent code support` is properly squashed in fc85336d1c9b5c2a5f42bc6a8789ca7918a8f48e `cmake: Add position independent code support` in this PR (branch `231024-linear`), not like in my local rebase where I moved it into 6bf981a560 `cmake: Build `bitcoind` executable` to avoid a conflict.

**Comment by hebasto** [comment]
@theuni @vasild 

Thank you for the reviewing!

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Pull request closed without merging**
