### PR TITLE
build: rename ENABLE_FUZZ to BUILD_FOR_FUZZING

### PR DESCRIPTION
**Pull request by vasild**
The name `ENABLE_FUZZ` is confusing because that option does not enable fuzzing. `-DSANITIZERS=fuzzer` is what enables fuzzing via libFuzzer (there are other fuzzing engines, enables by other means).

Fixes: https://github.com/bitcoin/bitcoin/issues/30318

### CODE REVIEW

**Comment by vasild** [comment]
Another possible name is `PREPARE_FOR_FUZZING`.

Should I change this to `fixup!` commit(s)?

**Comment by vasild** [comment]
@maflcko, updated the OP.

The way I understand it "fuzzing" is the ingenious search for new inputs to increase the code coverage.

> one can consider running a fixed set of inputs as fuzzing (without a fuzz engine)

I don't understand it that way. Also see https://www.erisian.com.au/bitcoin-core-dev/log-2024-06-20.html#l-265

**Comment by vasild** [comment]
Party :partying_face: table: https://gist.github.com/hebasto/2ef97d3a726bfce08ded9df07f7dab5e

**Comment by hebasto** [comment]
cc @dergoegge :)

**Comment by hebasto** [comment]
@vasild 

Please rebase.

**Review by dergoegge — APPROVED** [review]

**Comment by vasild** [comment]
`e93df1a1be...fa89f1c155`: rebase due to conflicts

**Review by hebasto — APPROVED** [review]
re-ACK fa89f1c1551619817b76807dfafa1625595502e1.

**Comment by hebasto** [comment]
> Party 🥳 table: https://gist.github.com/hebasto/2ef97d3a726bfce08ded9df07f7dab5e

Updated.

**Pull request merged**
