### PR TITLE
cmake: Backport changes from master

### PR DESCRIPTION
**Pull request by hebasto**
This PR mirrors https://github.com/bitcoin/bitcoin/pull/28845.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @fanquake @TheCharlatan @theuni

**Comment by hebasto** [comment]
> This PR mirrors [bitcoin#28845](https://github.com/bitcoin/bitcoin/pull/28845).

The https://github.com/bitcoin/bitcoin/pull/28845 has been merged now.

**Comment by hebasto** [comment]
Rebased.

**Review by TheCharlatan — APPROVED** [review]
ACK 78d410d8bc712d0e9d8157c40fc887fbabcc22e3

**Pull request merged**
