### PR TITLE
cmake: Port PR28783 from the master branch

### PR DESCRIPTION
**Pull request by hebasto**
The `-bind_at_load` has been removed since https://github.com/bitcoin/bitcoin/pull/28783.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @fanquake

**Comment by fanquake** [comment]
Is there an explanation for why the CMake check here: https://github.com/hebasto/bitcoin/pull/93#issuecomment-2126813895, is broken? Obviously removing this flag will fix this instance, but I assume the same behaviour will still happen with other flags?

**Comment by hebasto** [comment]
> Is there an explanation for why the CMake check here: [#93 (comment)](https://github.com/hebasto/bitcoin/pull/93#issuecomment-2126813895), is broken?

Not yet. This PR only mirrors the master branch.

**Comment by hebasto** [comment]
> Is there an explanation for why the CMake check here: [#93 (comment)](https://github.com/hebasto/bitcoin/pull/93#issuecomment-2126813895), is broken?

An explanation  is here: https://github.com/hebasto/bitcoin/pull/93#issuecomment-2127453157.

**Comment by hebasto** [comment]
Going to merge this basing on the discussion during today's call.

**Pull request merged**
