### PR TITLE
cmake: Replace `genbuild.sh` with `GenerateBuildInfo.cmake`

### PR DESCRIPTION
**Pull request by hebasto**
This PR replaces shell `share/genbuild.sh` script with CMake `GenerateBuildInfo.cmake` script, which works on all platforms, including Windows.

Fixes build on Windows after https://github.com/hebasto/bitcoin/pull/51.

Please note, that in the master branch, MSVC builds lack build info entirely.

Added a CI test to ensure equivalence of the script replacement.

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @fanquake @theuni @TheCharlatan @vasild @pablomartin4btc :)

**Review by pablomartin4btc — APPROVED** [review]
tACK 2e2a7b554251434be0de9b31d15a70a17cf45df7

Built on Ubuntu 22.04, ran `ctest`, functionals and executed `bitcoind -signet` up to full headers sync.

**Comment by vasild** [comment]
Light ACK, why not remove `share/genbuild.sh`?

**Comment by hebasto** [comment]
> Light ACK, why not remove `share/genbuild.sh`?

Sure. After transition to CMake is completed?

Right now it seems useful to keep it to ensure that `share/genbuild.sh` and the new CMake script produce the same headers.

**Review by pablomartin4btc — COMMENTED** [review]
tACK 2e2a7b554251434be0de9b31d15a70a17cf45df7

Built cross-compiled for Windows on WSL Ubuntu 22.04 ([instructions](https://github.com/hebasto/bitcoin/pull/31#issuecomment-1722338779)), binaries are fine and ran on Windows 11 Pro but 2 tests are failing running `ctest`, I've verified that's also happening on `cmake-staging` branch, so I've opened #55.

**Comment by hebasto** [comment]
> Fixes build on Windows after #51.

Going to merge this PR shortly to unlock Windows builds.

**Pull request merged**
