### PR TITLE
Lower collision risk in try_append_[linker|cxx]_flag

### PR DESCRIPTION
**Pull request by l0rinc**
Previously, `sqrt(16^4) ≈ 256` sources had a `50%` collision chance, now `sqrt(16^8) ≈ 65536` sources have the same collision probability.

While a false cache hit would likely be a severe bug and both before/after are quite unlikely, I think we can increase our confidence cheaply.

### CODE REVIEW

**Comment by theuni** [comment]
Hmm, why clamp it at all? I don't see any harm in just using the full hash?

**Comment by l0rinc** [comment]
I assumed it was some optimization, but I also vote for full hash, if that's an option

**Comment by hebasto** [comment]
> I assumed it was some optimization...

Rather an attempt to make variable names reasonably shorter.

**Comment by fanquake** [comment]
> Rather an attempt to make variable names reasonably shorter.

Are there length limits, or, what is the issue with longer names? It's not clear that, potentially subtle, random issues is a good trade off for shorter named variables.

**Comment by hebasto** [comment]
> > Rather an attempt to make variable names reasonably shorter.
> 
> Are there length limits, or, what is the issue with longer names?

CMake [doc](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#variables) does not specify any length limits.

**Comment by hebasto** [comment]
> Hmm, why clamp it at all? I don't see any harm in just using the full hash?

I've reviewed the current code and did not find any instances where the same source is checked more than once with the same result variable. Therefore, the hash suffix can be dropped altogether, unless I've overlooked something.

**Comment by l0rinc** [comment]
> Therefore, the hash suffix can be dropped altogether, unless I've overlooked something

I also noticed that I could only trigger that path via fuzzing, you're right, that seems to be the only case when SOURCE is defined: https://github.com/bitcoin/bitcoin/blob/8b6f1c4353836bae6aa683cbc65251165bd031ba/CMakeLists.txt#L383-L389.
So currently the values would be unique without the hash, but overwriting a source in the future would cause a false hit, so I think we should keep it - removing the substring.

On top of that, `try_append_cxx_flags` currently doesn't even need a `SOURCE` parameter (unless you think it's nice to make it symmetric with `try_append_linker_flag`).
Same for `IF_CHECK_FAILED`, seems unused in both cases, would simplify the code if we removed it:
```diff
diff --git a/cmake/module/TryAppendCXXFlags.cmake b/cmake/module/TryAppendCXXFlags.cmake
index 3d6089dda2..b00c5cb65a 100644
--- a/cmake/module/TryAppendCXXFlags.cmake
+++ b/cmake/module/TryAppendCXXFlags.cmake
@@ -32,12 +32,6 @@ Usage examples:
   )


-  try_append_cxx_flags("-Werror=return-type" TARGET core_interface
-    IF_CHECK_FAILED "-Wno-error=return-type"
-    SOURCE "#include <cassert>\nint f(){ assert(false); }"
-  )
-
-
 In configuration output, this function prints a string by the following pattern:

   -- Performing Test CXX_SUPPORTS_[flags]
@@ -48,8 +42,8 @@ function(try_append_cxx_flags flags)
   cmake_parse_arguments(PARSE_ARGV 1
     TACXXF                            # prefix
     "SKIP_LINK"                       # options
-    "TARGET;VAR;SOURCE;RESULT_VAR"    # one_value_keywords
-    "IF_CHECK_PASSED;IF_CHECK_FAILED" # multi_value_keywords
+    "TARGET;VAR;RESULT_VAR"           # one_value_keywords
+    "IF_CHECK_PASSED"
   )

   set(flags_as_string "${flags}")
@@ -59,17 +53,12 @@ function(try_append_cxx_flags flags)
   string(TOUPPER "${id_string}" id_string)

   set(source "int main() { return 0; }")
-  if(DEFINED TACXXF_SOURCE AND NOT TACXXF_SOURCE STREQUAL source)
-    set(source "${TACXXF_SOURCE}")
-    string(SHA256 source_hash "${source}")
-    string(SUBSTRING ${source_hash} 0 8 source_hash_head)
-    string(APPEND id_string _${source_hash_head})
-  endif()

   # This avoids running a linker.
   set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
   set(CMAKE_REQUIRED_FLAGS "${flags_as_string} ${working_compiler_werror_flag}")
   set(compiler_result CXX_SUPPORTS_${id_string})
+  message(STATUS "try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `${compiler_result}` on `${source}`") # TODO remove
   check_cxx_source_compiles("${source}" ${compiler_result})

   if(${compiler_result})
@@ -88,13 +77,6 @@ function(try_append_cxx_flags flags)
         string(STRIP "${${TACXXF_VAR}} ${flags_as_string}" ${TACXXF_VAR})
       endif()
     endif()
-  elseif(DEFINED TACXXF_IF_CHECK_FAILED)
-    if(DEFINED TACXXF_TARGET)
-      target_compile_options(${TACXXF_TARGET} INTERFACE ${TACXXF_IF_CHECK_FAILED})
-    endif()
-    if(DEFINED TACXXF_VAR)
-      string(STRIP "${${TACXXF_VAR}} ${TACXXF_IF_CHECK_FAILED}" ${TACXXF_VAR})
-    endif()
   endif()

   if(DEFINED TACXXF_VAR)
@@ -114,6 +96,7 @@ function(try_append_cxx_flags flags)
   set(CMAKE_REQUIRED_FLAGS "${flags_as_string}")
   set(CMAKE_REQUIRED_LINK_OPTIONS ${working_linker_werror_flag})
   set(linker_result LINKER_SUPPORTS_${id_string})
+  message(STATUS "try_append_cxx_flags: check_cxx_source_compiles called with linker_result `${linker_result}` on `${source}`") # TODO remove
   check_cxx_source_compiles("${source}" ${linker_result})

   if(${linker_result})
diff --git a/cmake/module/TryAppendLinkerFlag.cmake b/cmake/module/TryAppendLinkerFlag.cmake
index 9ed63c0c71..64fca8b60c 100644
--- a/cmake/module/TryAppendLinkerFlag.cmake
+++ b/cmake/module/TryAppendLinkerFlag.cmake
@@ -22,27 +22,27 @@ function(try_append_linker_flag flag)
     TALF                              # prefix
     ""                                # options
     "TARGET;VAR;SOURCE;RESULT_VAR"    # one_value_keywords
-    "IF_CHECK_PASSED;IF_CHECK_FAILED" # multi_value_keywords
+    "IF_CHECK_PASSED"
   )

-  string(MAKE_C_IDENTIFIER "${flag}" result)
-  string(TOUPPER "${result}" result)
-  string(PREPEND result LINKER_SUPPORTS_)
+  string(MAKE_C_IDENTIFIER "${flag}" linker_result)
+  string(TOUPPER "${linker_result}" linker_result)
+  string(PREPEND linker_result LINKER_SUPPORTS_)

   set(source "int main() { return 0; }")
   if(DEFINED TALF_SOURCE AND NOT TALF_SOURCE STREQUAL source)
     set(source "${TALF_SOURCE}")
     string(SHA256 source_hash "${source}")
-    string(SUBSTRING ${source_hash} 0 8 source_hash_head)
-    string(APPEND result _${source_hash_head})
+    string(APPEND linker_result _${source_hash})
   endif()

   # This forces running a linker.
   set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
   set(CMAKE_REQUIRED_LINK_OPTIONS ${flag} ${working_linker_werror_flag})
-  check_cxx_source_compiles("${source}" ${result})
+  message(STATUS "try_append_linker_flag: check_cxx_source_compiles called with linker_result `${linker_result}` on `${source}`") # TODO remove
+  check_cxx_source_compiles("${source}" ${linker_result})

-  if(${result})
+  if(${linker_result})
     if(DEFINED TALF_IF_CHECK_PASSED)
       if(DEFINED TALF_TARGET)
         target_link_options(${TALF_TARGET} INTERFACE ${TALF_IF_CHECK_PASSED})
@@ -58,13 +58,6 @@ function(try_append_linker_flag flag)
         string(STRIP "${${TALF_VAR}} ${flag}" ${TALF_VAR})
       endif()
     endif()
-  elseif(DEFINED TALF_IF_CHECK_FAILED)
-    if(DEFINED TALF_TARGET)
-      target_link_options(${TALF_TARGET} INTERFACE ${TACXXF_IF_CHECK_FAILED})
-    endif()
-    if(DEFINED TALF_VAR)
-      string(STRIP "${${TALF_VAR}} ${TACXXF_IF_CHECK_FAILED}" ${TALF_VAR})
-    endif()
   endif()

   if(DEFINED TALF_VAR)
@@ -72,7 +65,7 @@ function(try_append_linker_flag flag)
   endif()

   if(DEFINED TALF_RESULT_VAR)
-    set(${TALF_RESULT_VAR} "${${result}}" PARENT_SCOPE)
+    set(${TALF_RESULT_VAR} "${${linker_result}}" PARENT_SCOPE)
   endif()
 endfunction()
```

------


So keeping the debug messages above and running:
```bash
cmake -B build_fuzz \
   -DCMAKE_C_COMPILER="$(brew --prefix llvm)/bin/clang" \
   -DCMAKE_CXX_COMPILER="$(brew --prefix llvm)/bin/clang++" \
   -DBUILD_FOR_FUZZING=ON \
   -DSANITIZERS=undefined,address,fuzzer \
   -DAPPEND_LDFLAGS=-Wl,-no_warn_duplicate_libraries
```

I'm getting:
```
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WERROR` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__FATAL_WARNINGS` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__DEAD_STRIP` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__DEAD_STRIP_DYLIBS` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__HEADERPAD_MAX_INSTALL_NAMES` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__FSANITIZE_UNDEFINED_ADDRESS_FUZZER_a797852b32447d9d3594b7f06efe65790daaefcbefce4144d7b1f480f6fa4b6a` on `
      #include <cstdint>
      #include <cstddef>
      extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) { return 0; }
      __attribute__((weak)) // allow for libFuzzer linking
      int main() { return 0; }
    `
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FDEBUG_PREFIX_MAP_A_B` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FMACRO_PREFIX_MAP_A_B` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WALL` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WEXTRA` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WGNU` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WFORMAT__WFORMAT_SECURITY` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WVLA` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WSHADOW_FIELD` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WTHREAD_SAFETY` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WLOOP_ANALYSIS` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WREDUNDANT_DECLS` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WUNUSED_MEMBER_FUNCTION` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WDATE_TIME` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WCONDITIONAL_UNINITIALIZED` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WDUPLICATED_BRANCHES` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WDUPLICATED_COND` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WLOGICAL_OP` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WOVERLOADED_VIRTUAL` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WSUGGEST_OVERRIDE` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WIMPLICIT_FALLTHROUGH` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WUNREACHABLE_CODE` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WDOCUMENTATION` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WSELF_ASSIGN` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WUNDEF` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WUNUSED_PARAMETER` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FNO_EXTENDED_IDENTIFIERS` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FSTACK_REUSE_NONE` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__U_FORTIFY_SOURCE__D_FORTIFY_SOURCE_3` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__U_FORTIFY_SOURCE__D_FORTIFY_SOURCE_3` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__WSTACK_PROTECTOR` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FSTACK_PROTECTOR_ALL` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__FSTACK_PROTECTOR_ALL` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FCF_PROTECTION_FULL` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__FSTACK_CLASH_PROTECTION` on `int main() { return 0; }`
-- try_append_cxx_flags: check_cxx_source_compiles called with compiler_result `CXX_SUPPORTS__MBRANCH_PROTECTION_BTI` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL___ENABLE_RELOC_SECTION` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL___DYNAMICBASE` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL___NXCOMPAT` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL___HIGH_ENTROPY_VA` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__Z_RELRO` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__Z_NOW` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__Z_SEPARATE_CODE` on `int main() { return 0; }`
-- try_append_linker_flag: check_cxx_source_compiles called with linker_result `LINKER_SUPPORTS__WL__FIXUP_CHAINS` on `int main() { return 0; }`
```

If you're okay with the patch I can update the PR with a few more commits, explaining the changes.

**Comment by hebasto** [comment]
Since https://github.com/bitcoin/bitcoin/pull/30454 has been merged, further development in this repository no longer makes sense. Please consider moving this PR to the main repository.

**Comment by l0rinc** [comment]
Applied suggestions and moved it to https://github.com/bitcoin/bitcoin/pull/30732

**Pull request closed without merging**
