### PR TITLE
Rebased `cmake-staging` branch (post PR#10)

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/tree/cmake-staging) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/5150e280103dd41c8a438ce72359b0f25ff23a2f) one with squashed "FIXUP" commits.

Rebase phase: [`cmake-staging/pr11-init`](https://github.com/hebasto/bitcoin/commits/cmake-staging/pr11-init) --> [`cmake-staging/pr11-rebased`](https://github.com/hebasto/bitcoin/commits/cmake-staging/pr11-rebased). Fixed conflicts with the following PRs:
- https://github.com/bitcoin/bitcoin/pull/25781
- https://github.com/bitcoin/bitcoin/pull/26177
- https://github.com/bitcoin/bitcoin/pull/27118
- https://github.com/bitcoin/bitcoin/pull/27150
- https://github.com/bitcoin/bitcoin/pull/27238

Squash phase: [`cmake-staging/pr11-rebased`](https://github.com/hebasto/bitcoin/commits/cmake-staging/pr11-rebased) --> [`cmake-staging/pr11-squashed`](https://github.com/hebasto/bitcoin/commits/cmake-staging/pr11-squashed). A diff must be zero :)

## Expected to work:

Cross-compiling for Windows:
```
make -C depends HOST=x86_64-w64-mingw32 NO_QT=1 NO_WALLET=1 NO_ZMQ=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1
cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=depends/x86_64-w64-mingw32/share/toolchain.cmake
cmake --build build
```

Cross-compiling for macOS, arm64:
```
make -C depends HOST=arm64-apple-darwin NO_QT=1 NO_WALLET=1 NO_ZMQ=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1
cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=depends/arm64-apple-darwin/share/toolchain.cmake
cmake --build build
```

Cross-compiling with libc++:
```
$ make -C depends CC=clang CXX="clang++ -stdlib=libc++" NO_QT=1 NO_WALLET=1 NO_ZMQ=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1
cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=depends/x86_64-pc-linux-gnu/share/toolchain.cmake
cmake --build build
```

---

Previous linearization PR:
- https://github.com/hebasto/bitcoin/pull/8

### CODE REVIEW

**Comment by hebasto** [comment]
@vasild @TheCharlatan @theStack @theuni @willcl-ark

Ready for extensive testing :)

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
> Were there any fixups or changes other than the squashing?

Yes. PRs from the PR description introduced changes in the source tree that were accommodated here.

**Comment by TheCharlatan** [comment]
LGTM, I checked that the fixup commit made it to the right place with
```
diff <(git show 00c44c815cd22c9d924e245bb0e01c34b561a2e3) <(git show 91f28a6a961f962e0408130cbc46d9aa8cc4b84b)
```

**Review by theuni — APPROVED** [review]
ACK 5b25bcd8099b4cc0ac9cb76246885d093fe3c791

**Comment by hebasto** [comment]
This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Pull request closed without merging**
