### PR TITLE
cmake: Add LTO functionality

### PR DESCRIPTION
**Pull request by hebasto**
The `LTO_FLAGS` CMake variable might be used to override CMake's default LTO flags.

The following build system configuration:
```
cmake -B build -DLTO=ON -DLTO_FLAGS="-flto"
```
is comparable with the master branch amended with https://github.com/bitcoin/bitcoin/pull/28876.

### CODE REVIEW

**Comment by hebasto** [comment]
Rebased.

**Comment by fanquake** [comment]
Repeating my comments from https://github.com/bitcoin/bitcoin/pull/28876. I'm not a fan of this interface. If we are going to have a dedicated LTO option, it shouldn't also require manually passing flags into non-standard variables.

It's also not clear to me why:
> cmake -B build -DLTO=ON -DLTO_FLAGS="-flto"

is any better than just:
> cmake -B build CXX_FLAGS="-flto"

In this branch, is `LTO_FLAGS` meant to be for any flags, i.e compile and link?

**Comment by hebasto** [comment]
> It's also not clear to me why:
> 
> > cmake -B build -DLTO=ON -DLTO_FLAGS="-flto"
> 
> is any better than just:
> 
> > cmake -B build CXX_FLAGS="-flto"
> 
> In this branch, is `LTO_FLAGS` meant to be for any flags, i.e compile and link?

1. In this branch, the `LTO_FLAGS` is meant to be for flags that are supposed to be passed to a compiler driver for any language (C or C++) in any mode (compiling or linking).

2. The default CMake LTO flags are better for everyday developer builds than just `-flto` for both GCC and Clang. They need to be adjusted only for release builds to be on-par with the master branch.

3. The `LTO` CMake variable was chosen to accomplish feature parity requirement for a new build system. Agree with you that `LTO_FLAGS` looks ugly.

4. Both ways:
```
CXXFLAGS="-flto" cmake -B build
```
and
```
cmake -B build -DCMAKE_CXX_FLAGS="-flto"
```
have the common drawback, which is no support for C code. That means that all object files in the `build/CMakeFiles/secp256k1.dir/src/secp256k1/src` are compiled without LTO flags.

---

> I'm not a fan of this interface.

Happy to hear other interface ideas / prototypes :)

**Comment by fanquake** [comment]
> 1. 

Right. So we've still got to use LDFLAGS pass through normal LTO link options, with your current approach?

> 2. 

What the default CMake LTO flags? Why are they better? Are they stable (not changing from release to release)

> which is no support for C code.

Why wouldn't it support C code; that's what CFLAGS is for? I only omitted it here to simplify examples.

**Comment by hebasto** [comment]
> What are the default CMake LTO flags? Why are they better?

For GCC:
```
-flto=auto -fno-fat-lto-objects
```

with the main benefit of parallelizing of LTRANS jobs, which in turn means:
- quicker build
- no "lto-wrapper: warning: using serial compilation of 128 LTRANS jobs" warnings

For Clang:
```
-flto-thin
```
with benefits as follows:
- quicker build
- compatibility with OSS-Fuzz

>  Are they stable (not changing from release to release)?

No, they are not.

---

If I understand your point correctly, this PR could be closed and all needed LTO flags are to be provided via standard variable, right?

**Comment by fanquake** [comment]
I think the PR should stay open for further discussion/other ideas, but yes, my main point is that we shouldn't be creating a special interface, for a subset of optimisation flags, without a good reason too. Especially if it might still requires you to use standard env vars anyways.

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
Marking this PR as a draft in the light of the https://github.com/bitcoin/bitcoin/pull/29185.

**Comment by hebasto** [comment]
Closing. See https://github.com/bitcoin/bitcoin/pull/29185.

**Pull request closed without merging**
