### PR TITLE
cmake: Skip superfluous PIC/PIE warning for Windows

### PR DESCRIPTION
**Pull request by hebasto**
PIC/PIE is not a thing in Windows PE format. Therefore, warnings are rather making noise than providing valuable feedback.

### CODE REVIEW

**Comment by hebasto** [comment]
Rebased.

**Comment by theuni** [comment]
It's frustrating that CMake doesn't just know this. It's also frustrating that `check_pie_supported` seems to just be wrong for Windows? I wonder if we should upstream a fix/change?

FWIW, pic/pie is default on for macOS, so if we're not already getting warnings there, we probably will at some point, so we may as well include that here as well.

**Comment by TheCharlatan** [comment]
> If guarding the whole code block with if(NOT WIN32) looks unclear, maybe do it for message(WARNING ...) only?

That seems preferable to me, maybe also with a small comment explaining why?

**Comment by hebasto** [comment]
Rebased.

Addressed @TheCharlatan's [comment](https://github.com/hebasto/bitcoin/pull/58#issuecomment-1849882144).

**Review by TheCharlatan — APPROVED** [review]
ACK 52447c39c835a50a552a724cc90068ef286d965a

**Comment by theuni** [comment]
Post-merge ACK. Thanks for the explanation, @hebasto, I had indeed misunderstood.

**Pull request merged**
