### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/commit/3c740846bf0ffb8eecb56585cb35d936d73f3af8) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/d7333ece15b8a9c941af072cebc210b099900d0e) branch, which includes the main build system changes, with the squashed "!fixup" commits.

Steps to reproduce:
1. Run the command as follows:
```
git checkout 3c740846bf0ffb8eecb56585cb35d936d73f3af8
git rebase -i --autosquash d7333ece15b8a9c941af072cebc210b099900d0e
```
There are a few conflicts that have to be resolved.

2. Squash "[FIXUP]" commits that were not handled automatically (there must be a zero-diff change).

3. Reorder commits to make their history suitable for https://github.com/bitcoin/bitcoin/pull/30454 (there must be a zero-diff change).

### CODE REVIEW

**Comment by m3dwards** [comment]
ACK a247573c8f7652b30843e3114d597645694c1dec

Didn't manage to get a clean rebase but I can see the code I have extra was removed here: https://github.com/hebasto/bitcoin/pull/307/files so it must be my poor rebasing skills again.

Guix is building

**Comment by hebasto** [comment]
@m3dwards 

Thank you for your review!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
5c2bc3135419814a563d30ccc130a75b8dbacc3308394c59de0b4d3a85bfacd3  guix-build-a247573c8f76/output/aarch64-linux-gnu/SHA256SUMS.part
39340772554a0d4b1028627916fe86fcf428472952141bdb4f4fe96e88ec4ff2  guix-build-a247573c8f76/output/aarch64-linux-gnu/bitcoin-a247573c8f76-aarch64-linux-gnu-debug.tar.gz
51719dd9095477d74bb1c50333615e46ce15e491a841ee73753aabbb6c73577b  guix-build-a247573c8f76/output/aarch64-linux-gnu/bitcoin-a247573c8f76-aarch64-linux-gnu.tar.gz
336feb70ec077679fa08c3ab9338e8b31c317fd3d1d2575243b6379244937ac2  guix-build-a247573c8f76/output/arm-linux-gnueabihf/SHA256SUMS.part
3c91da4f74ac8c3d55971fbcb676732eee766f600fb4220066224327f275722f  guix-build-a247573c8f76/output/arm-linux-gnueabihf/bitcoin-a247573c8f76-arm-linux-gnueabihf-debug.tar.gz
9c258dfa9479ff50d2c995e3e0bc1f4158abd62707d98db23f52400ebe662484  guix-build-a247573c8f76/output/arm-linux-gnueabihf/bitcoin-a247573c8f76-arm-linux-gnueabihf.tar.gz
964b76b8ec018cc3f380adfd93b143115ad6128aade3195c64106b6360579b78  guix-build-a247573c8f76/output/arm64-apple-darwin/SHA256SUMS.part
d026fe409d12eaaa551eb41ee913c6a3968b71b30000e883296846f1d2639734  guix-build-a247573c8f76/output/arm64-apple-darwin/bitcoin-a247573c8f76-arm64-apple-darwin-unsigned.tar.gz
62c3264a9a45410ce03df57092d0e6b63c3407c561a9d9c3fcd8aab97907d44d  guix-build-a247573c8f76/output/arm64-apple-darwin/bitcoin-a247573c8f76-arm64-apple-darwin-unsigned.zip
0939ec31268be1a50fff4513b3dc02cf82ee64c0dca8b3ac633f0d6a0a8140fd  guix-build-a247573c8f76/output/arm64-apple-darwin/bitcoin-a247573c8f76-arm64-apple-darwin.tar.gz
611446c47246e326bf28902147c90fcb54aaf84a83cb638c3eda26ca37798e7a  guix-build-a247573c8f76/output/dist-archive/bitcoin-a247573c8f76.tar.gz
612165dc248315d385cb080e611516feddb0ec6652a29045fb5e003685cbd0cc  guix-build-a247573c8f76/output/powerpc64-linux-gnu/SHA256SUMS.part
5fdf7e2c72cac6059864ed8fe130c0eba0e41217d917d0030277e7b25685f7da  guix-build-a247573c8f76/output/powerpc64-linux-gnu/bitcoin-a247573c8f76-powerpc64-linux-gnu-debug.tar.gz
42012cb080d4a57d26688b85186864e74d18ddb8199659a3cd91ed8f5881a744  guix-build-a247573c8f76/output/powerpc64-linux-gnu/bitcoin-a247573c8f76-powerpc64-linux-gnu.tar.gz
e2e325ac379f8e96bc39a690ee92cd0b3e837d2fca32704beb42d03910be01ed  guix-build-a247573c8f76/output/riscv64-linux-gnu/SHA256SUMS.part
20f62341e951e0803b7c76f91bff25a95740cd91e5de189b95a8b40e7c6e9546  guix-build-a247573c8f76/output/riscv64-linux-gnu/bitcoin-a247573c8f76-riscv64-linux-gnu-debug.tar.gz
9c12a7a45b98c15ffaef9fa6d20e9a3517ec4d99a3c7bed0648a77010321b6c1  guix-build-a247573c8f76/output/riscv64-linux-gnu/bitcoin-a247573c8f76-riscv64-linux-gnu.tar.gz
7fbaa2ba40fa81edf9a0b8f57fb27a041b8d726be89dda259ffb2947fbd0b658  guix-build-a247573c8f76/output/x86_64-apple-darwin/SHA256SUMS.part
11241a2359b3cb7d0bb5a334c76a38d167fb8814d836db209df05ff335b6f964  guix-build-a247573c8f76/output/x86_64-apple-darwin/bitcoin-a247573c8f76-x86_64-apple-darwin-unsigned.tar.gz
54c08c37af8b03397bee92558d838081ad5e4e57e0bdb9e8e59cb0c483899947  guix-build-a247573c8f76/output/x86_64-apple-darwin/bitcoin-a247573c8f76-x86_64-apple-darwin-unsigned.zip
bd93219ef937152f511106a9c780ac550a6e235cc2695d58d78078832da1ba77  guix-build-a247573c8f76/output/x86_64-apple-darwin/bitcoin-a247573c8f76-x86_64-apple-darwin.tar.gz
76c09f001e038891f4532f915ccf232a018e41e15765cbcc07ec2f95db6835ab  guix-build-a247573c8f76/output/x86_64-linux-gnu/SHA256SUMS.part
c91f1e6590d69371ecc1c77d3c91b2b57d048c9c303550a34a4be82b7b231378  guix-build-a247573c8f76/output/x86_64-linux-gnu/bitcoin-a247573c8f76-x86_64-linux-gnu-debug.tar.gz
da75dbc23ea475fb24b9badaf37729591193f2f6faddc37e52250c0ce28731b2  guix-build-a247573c8f76/output/x86_64-linux-gnu/bitcoin-a247573c8f76-x86_64-linux-gnu.tar.gz
4146dcf24c40406d657619d318df9bf04c8d534352513f7b2edb29515cac586a  guix-build-a247573c8f76/output/x86_64-w64-mingw32/SHA256SUMS.part
a2da7cc31088937a7c685443550401ed49bc264a3c62c7ce935d135e8964f1f6  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64-debug.zip
65e44df75e0171b029a6148c2c978d42dd265f42d8e4c184d62b9a0e114dbc51  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64-setup-unsigned.exe
efa39e967495a2c9b9a4b0ec36ff2ebb988cf862ba4c6ad51d3a85a5bb2ba63b  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64-unsigned.tar.gz
f5357a598f406eff6bc4d88356978842c9df780e09daa58bd703c5ebe11c8076  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64.zip
```

**Comment by m3dwards** [comment]
Post close guix build (x86)

```shell
5c2bc3135419814a563d30ccc130a75b8dbacc3308394c59de0b4d3a85bfacd3  guix-build-a247573c8f76/output/aarch64-linux-gnu/SHA256SUMS.part
39340772554a0d4b1028627916fe86fcf428472952141bdb4f4fe96e88ec4ff2  guix-build-a247573c8f76/output/aarch64-linux-gnu/bitcoin-a247573c8f76-aarch64-linux-gnu-debug.tar.gz
51719dd9095477d74bb1c50333615e46ce15e491a841ee73753aabbb6c73577b  guix-build-a247573c8f76/output/aarch64-linux-gnu/bitcoin-a247573c8f76-aarch64-linux-gnu.tar.gz
336feb70ec077679fa08c3ab9338e8b31c317fd3d1d2575243b6379244937ac2  guix-build-a247573c8f76/output/arm-linux-gnueabihf/SHA256SUMS.part
3c91da4f74ac8c3d55971fbcb676732eee766f600fb4220066224327f275722f  guix-build-a247573c8f76/output/arm-linux-gnueabihf/bitcoin-a247573c8f76-arm-linux-gnueabihf-debug.tar.gz
9c258dfa9479ff50d2c995e3e0bc1f4158abd62707d98db23f52400ebe662484  guix-build-a247573c8f76/output/arm-linux-gnueabihf/bitcoin-a247573c8f76-arm-linux-gnueabihf.tar.gz
964b76b8ec018cc3f380adfd93b143115ad6128aade3195c64106b6360579b78  guix-build-a247573c8f76/output/arm64-apple-darwin/SHA256SUMS.part
d026fe409d12eaaa551eb41ee913c6a3968b71b30000e883296846f1d2639734  guix-build-a247573c8f76/output/arm64-apple-darwin/bitcoin-a247573c8f76-arm64-apple-darwin-unsigned.tar.gz
62c3264a9a45410ce03df57092d0e6b63c3407c561a9d9c3fcd8aab97907d44d  guix-build-a247573c8f76/output/arm64-apple-darwin/bitcoin-a247573c8f76-arm64-apple-darwin-unsigned.zip
0939ec31268be1a50fff4513b3dc02cf82ee64c0dca8b3ac633f0d6a0a8140fd  guix-build-a247573c8f76/output/arm64-apple-darwin/bitcoin-a247573c8f76-arm64-apple-darwin.tar.gz
611446c47246e326bf28902147c90fcb54aaf84a83cb638c3eda26ca37798e7a  guix-build-a247573c8f76/output/dist-archive/bitcoin-a247573c8f76.tar.gz
612165dc248315d385cb080e611516feddb0ec6652a29045fb5e003685cbd0cc  guix-build-a247573c8f76/output/powerpc64-linux-gnu/SHA256SUMS.part
5fdf7e2c72cac6059864ed8fe130c0eba0e41217d917d0030277e7b25685f7da  guix-build-a247573c8f76/output/powerpc64-linux-gnu/bitcoin-a247573c8f76-powerpc64-linux-gnu-debug.tar.gz
42012cb080d4a57d26688b85186864e74d18ddb8199659a3cd91ed8f5881a744  guix-build-a247573c8f76/output/powerpc64-linux-gnu/bitcoin-a247573c8f76-powerpc64-linux-gnu.tar.gz
e2e325ac379f8e96bc39a690ee92cd0b3e837d2fca32704beb42d03910be01ed  guix-build-a247573c8f76/output/riscv64-linux-gnu/SHA256SUMS.part
20f62341e951e0803b7c76f91bff25a95740cd91e5de189b95a8b40e7c6e9546  guix-build-a247573c8f76/output/riscv64-linux-gnu/bitcoin-a247573c8f76-riscv64-linux-gnu-debug.tar.gz
9c12a7a45b98c15ffaef9fa6d20e9a3517ec4d99a3c7bed0648a77010321b6c1  guix-build-a247573c8f76/output/riscv64-linux-gnu/bitcoin-a247573c8f76-riscv64-linux-gnu.tar.gz
7fbaa2ba40fa81edf9a0b8f57fb27a041b8d726be89dda259ffb2947fbd0b658  guix-build-a247573c8f76/output/x86_64-apple-darwin/SHA256SUMS.part
11241a2359b3cb7d0bb5a334c76a38d167fb8814d836db209df05ff335b6f964  guix-build-a247573c8f76/output/x86_64-apple-darwin/bitcoin-a247573c8f76-x86_64-apple-darwin-unsigned.tar.gz
54c08c37af8b03397bee92558d838081ad5e4e57e0bdb9e8e59cb0c483899947  guix-build-a247573c8f76/output/x86_64-apple-darwin/bitcoin-a247573c8f76-x86_64-apple-darwin-unsigned.zip
bd93219ef937152f511106a9c780ac550a6e235cc2695d58d78078832da1ba77  guix-build-a247573c8f76/output/x86_64-apple-darwin/bitcoin-a247573c8f76-x86_64-apple-darwin.tar.gz
76c09f001e038891f4532f915ccf232a018e41e15765cbcc07ec2f95db6835ab  guix-build-a247573c8f76/output/x86_64-linux-gnu/SHA256SUMS.part
c91f1e6590d69371ecc1c77d3c91b2b57d048c9c303550a34a4be82b7b231378  guix-build-a247573c8f76/output/x86_64-linux-gnu/bitcoin-a247573c8f76-x86_64-linux-gnu-debug.tar.gz
da75dbc23ea475fb24b9badaf37729591193f2f6faddc37e52250c0ce28731b2  guix-build-a247573c8f76/output/x86_64-linux-gnu/bitcoin-a247573c8f76-x86_64-linux-gnu.tar.gz
4146dcf24c40406d657619d318df9bf04c8d534352513f7b2edb29515cac586a  guix-build-a247573c8f76/output/x86_64-w64-mingw32/SHA256SUMS.part
a2da7cc31088937a7c685443550401ed49bc264a3c62c7ce935d135e8964f1f6  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64-debug.zip
65e44df75e0171b029a6148c2c978d42dd265f42d8e4c184d62b9a0e114dbc51  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64-setup-unsigned.exe
efa39e967495a2c9b9a4b0ec36ff2ebb988cf862ba4c6ad51d3a85a5bb2ba63b  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64-unsigned.tar.gz
f5357a598f406eff6bc4d88356978842c9df780e09daa58bd703c5ebe11c8076  guix-build-a247573c8f76/output/x86_64-w64-mingw32/bitcoin-a247573c8f76-win64.zip
```

**Pull request closed without merging**
