### PR TITLE
cmake: Regular rebasing of the `cmake-staging` branch

### PR DESCRIPTION
**Pull request by hebasto**
This is the [cmake-staging](https://github.com/hebasto/bitcoin/commit/bdaa036ca40b2d67f4d196c6b460da92f7ce194a) branch rebased on the recent [bitcoin/master](https://github.com/bitcoin/bitcoin/commit/07720b1cdd77399f32124641dbe1dd267eb0cf8b) one, which includes the main build system changes, with the squashed "!fixup" commits.

Steps to reproduce:
1. Run the command as follows:
```
git checkout bdaa036ca40b2d67f4d196c6b460da92f7ce194a
git rebase -i --autosquash 07720b1cdd77399f32124641dbe1dd267eb0cf8b
```
There is a conflict that has to be resolved.

2. Reorder the recent commits to pop up the CI one.

---

The build system related changes from the following PRs:
- https://github.com/bitcoin/bitcoin/pull/28981
- https://github.com/bitcoin/bitcoin/pull/29081
- https://github.com/bitcoin/bitcoin/pull/29786
- https://github.com/bitcoin/bitcoin/pull/29815
- https://github.com/bitcoin/bitcoin/pull/29823

 are to be backported in dedicated PRs shortly after approving this one.

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @m3dwards @TheCharlatan @pablomartin4btc @vasild :)

**Comment by hebasto** [comment]
My Guix builds:
```
8a814414f1ded781a4a1686c45ee9ef496c23f55476de299675a681eaf0449a8  guix-build-af998da072f0/output/aarch64-linux-gnu/SHA256SUMS.part
ed28ca2a53077f6220ef0923525598a84db4c06287ce9d3f8f936dedc4a1aefe  guix-build-af998da072f0/output/aarch64-linux-gnu/bitcoin-af998da072f0-aarch64-linux-gnu-debug.tar.gz
e1f6fef3580f6abb6b4dc7ce75f55f0411c17cf67f5a9f1346bf5322a063d0b9  guix-build-af998da072f0/output/aarch64-linux-gnu/bitcoin-af998da072f0-aarch64-linux-gnu.tar.gz
07ea2f84b89d5027827f271cfaba5348424f914fad41040daab58a21d1b17bfe  guix-build-af998da072f0/output/arm-linux-gnueabihf/SHA256SUMS.part
130125f4c8feeef68701f7dc1a64280d5faa8eae34ff8a7f5a6b68de731a38a0  guix-build-af998da072f0/output/arm-linux-gnueabihf/bitcoin-af998da072f0-arm-linux-gnueabihf-debug.tar.gz
6cbeea795f7103281b5e8498074522efb788b48c220710b223531a26a213bc42  guix-build-af998da072f0/output/arm-linux-gnueabihf/bitcoin-af998da072f0-arm-linux-gnueabihf.tar.gz
2876c737c7a22a23ed7393f352bac7954b358fbb799f9dbafdef4edd5f1b59ca  guix-build-af998da072f0/output/arm64-apple-darwin/SHA256SUMS.part
058cf37206f77a4c4a41087780c035fa239b82cf8df4260060ebc092bc2a81e5  guix-build-af998da072f0/output/arm64-apple-darwin/bitcoin-af998da072f0-arm64-apple-darwin-unsigned.tar.gz
e4d346f780687658fa05fc445dd42fa43ad4893012c64972e37471a05646fc1e  guix-build-af998da072f0/output/arm64-apple-darwin/bitcoin-af998da072f0-arm64-apple-darwin-unsigned.zip
1f242a96230f0700b8ea515f3994ce88df6152d6787acf1dd59c8500bb7048fc  guix-build-af998da072f0/output/arm64-apple-darwin/bitcoin-af998da072f0-arm64-apple-darwin.tar.gz
c743c73bdc6cc87c28e4648e3563baed85d9decc324476ba542b8e25b84955ff  guix-build-af998da072f0/output/dist-archive/bitcoin-af998da072f0.tar.gz
f1d19899f5e283dac853a38dadcb6895141c2f220e6485fd3793acdb2a2d426c  guix-build-af998da072f0/output/powerpc64-linux-gnu/SHA256SUMS.part
19ac54f0d59fefbf58c879edf4e07aa5259605ab6b26778084d145320374508d  guix-build-af998da072f0/output/powerpc64-linux-gnu/bitcoin-af998da072f0-powerpc64-linux-gnu-debug.tar.gz
d316720fc8a2680a7d068087e6dbf41c7f5c0c82e2d09b550512bf292b883b96  guix-build-af998da072f0/output/powerpc64-linux-gnu/bitcoin-af998da072f0-powerpc64-linux-gnu.tar.gz
30e290e8b81450c4b43a89ea123d42cbde261efc9ac48f33787f5f65c0cd480f  guix-build-af998da072f0/output/riscv64-linux-gnu/SHA256SUMS.part
efb86cb221252b88f2e561f575ac51a9c905dbf8bdde72c6d531062dda5178be  guix-build-af998da072f0/output/riscv64-linux-gnu/bitcoin-af998da072f0-riscv64-linux-gnu-debug.tar.gz
3a785b732cb3bd060fe5fd976312f43590c150ec5975c6c0f081a891664335c3  guix-build-af998da072f0/output/riscv64-linux-gnu/bitcoin-af998da072f0-riscv64-linux-gnu.tar.gz
ff0eb7032334e83ee49ac71e3d6e8e5254312bf51a978519186568b028fb3397  guix-build-af998da072f0/output/x86_64-apple-darwin/SHA256SUMS.part
864df3529d2c58d27855ed956945cdd5ba95d4ebfbc8cfcc8dc36b42fa35153f  guix-build-af998da072f0/output/x86_64-apple-darwin/bitcoin-af998da072f0-x86_64-apple-darwin-unsigned.tar.gz
065c8524a11be7d39aa6873afedc204ed9aefd041010cc5aaf38bfdb7e8d5ae7  guix-build-af998da072f0/output/x86_64-apple-darwin/bitcoin-af998da072f0-x86_64-apple-darwin-unsigned.zip
a9e53a906c8aa0760fc819b17e504d7d96fac117de57ab1e1d2f8582b3e64b99  guix-build-af998da072f0/output/x86_64-apple-darwin/bitcoin-af998da072f0-x86_64-apple-darwin.tar.gz
0eb02af52fe7dce373e2f797e5f12f27daeef2a0881d37507fe9fcac1fa47edc  guix-build-af998da072f0/output/x86_64-linux-gnu/SHA256SUMS.part
4b2d7d7ba4759a88898791064eb50aeccdd1b53ad5bba82f60e6207961ac241e  guix-build-af998da072f0/output/x86_64-linux-gnu/bitcoin-af998da072f0-x86_64-linux-gnu-debug.tar.gz
7e77275871af4845820e6681671d4e1be7d3b26669bb394fb0fa7cb3ac19f9a5  guix-build-af998da072f0/output/x86_64-linux-gnu/bitcoin-af998da072f0-x86_64-linux-gnu.tar.gz
7674627f30c9660d97c8d0b21fa7b5fe59cd7282af5eb8cb3d5d928bca85b566  guix-build-af998da072f0/output/x86_64-w64-mingw32/SHA256SUMS.part
85e363c3b24851cc30cb912039492adc3d9d85b2f545d936b54212670af325fc  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64-debug.zip
d57571dd880e0f1dcd24f0f55560bdd0559f55a28aea013d0da41f551d34b152  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64-setup-unsigned.exe
dc534082714bb978499c2aa44207158a71a29d9bd7cab522cde3fd3629244e66  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64-unsigned.tar.gz
25b474a9c1debd04dd4055afa070952db3e95b303c3f80cfe3313884861a3471  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64.zip
```

**Review by pablomartin4btc — APPROVED** [review]
ACK af998da072f09e47e5fda0489b62c8832ab22e7e

<details>
<summary>My Guix builds match yours.</summary>

```

8a814414f1ded781a4a1686c45ee9ef496c23f55476de299675a681eaf0449a8  guix-build-af998da072f0/output/aarch64-linux-gnu/SHA256SUMS.part
ed28ca2a53077f6220ef0923525598a84db4c06287ce9d3f8f936dedc4a1aefe  guix-build-af998da072f0/output/aarch64-linux-gnu/bitcoin-af998da072f0-aarch64-linux-gnu-debug.tar.gz
e1f6fef3580f6abb6b4dc7ce75f55f0411c17cf67f5a9f1346bf5322a063d0b9  guix-build-af998da072f0/output/aarch64-linux-gnu/bitcoin-af998da072f0-aarch64-linux-gnu.tar.gz

07ea2f84b89d5027827f271cfaba5348424f914fad41040daab58a21d1b17bfe  guix-build-af998da072f0/output/arm-linux-gnueabihf/SHA256SUMS.part
130125f4c8feeef68701f7dc1a64280d5faa8eae34ff8a7f5a6b68de731a38a0  guix-build-af998da072f0/output/arm-linux-gnueabihf/bitcoin-af998da072f0-arm-linux-gnueabihf-debug.tar.gz
6cbeea795f7103281b5e8498074522efb788b48c220710b223531a26a213bc42  guix-build-af998da072f0/output/arm-linux-gnueabihf/bitcoin-af998da072f0-arm-linux-gnueabihf.tar.gz

2876c737c7a22a23ed7393f352bac7954b358fbb799f9dbafdef4edd5f1b59ca  guix-build-af998da072f0/output/arm64-apple-darwin/SHA256SUMS.part
058cf37206f77a4c4a41087780c035fa239b82cf8df4260060ebc092bc2a81e5  guix-build-af998da072f0/output/arm64-apple-darwin/bitcoin-af998da072f0-arm64-apple-darwin-unsigned.tar.gz
e4d346f780687658fa05fc445dd42fa43ad4893012c64972e37471a05646fc1e  guix-build-af998da072f0/output/arm64-apple-darwin/bitcoin-af998da072f0-arm64-apple-darwin-unsigned.zip
1f242a96230f0700b8ea515f3994ce88df6152d6787acf1dd59c8500bb7048fc  guix-build-af998da072f0/output/arm64-apple-darwin/bitcoin-af998da072f0-arm64-apple-darwin.tar.gz

c743c73bdc6cc87c28e4648e3563baed85d9decc324476ba542b8e25b84955ff  guix-build-af998da072f0/output/dist-archive/bitcoin-af998da072f0.tar.gz

f1d19899f5e283dac853a38dadcb6895141c2f220e6485fd3793acdb2a2d426c  guix-build-af998da072f0/output/powerpc64-linux-gnu/SHA256SUMS.part
19ac54f0d59fefbf58c879edf4e07aa5259605ab6b26778084d145320374508d  guix-build-af998da072f0/output/powerpc64-linux-gnu/bitcoin-af998da072f0-powerpc64-linux-gnu-debug.tar.gz
d316720fc8a2680a7d068087e6dbf41c7f5c0c82e2d09b550512bf292b883b96  guix-build-af998da072f0/output/powerpc64-linux-gnu/bitcoin-af998da072f0-powerpc64-linux-gnu.tar.gz

30e290e8b81450c4b43a89ea123d42cbde261efc9ac48f33787f5f65c0cd480f  guix-build-af998da072f0/output/riscv64-linux-gnu/SHA256SUMS.part
efb86cb221252b88f2e561f575ac51a9c905dbf8bdde72c6d531062dda5178be  guix-build-af998da072f0/output/riscv64-linux-gnu/bitcoin-af998da072f0-riscv64-linux-gnu-debug.tar.gz
3a785b732cb3bd060fe5fd976312f43590c150ec5975c6c0f081a891664335c3  guix-build-af998da072f0/output/riscv64-linux-gnu/bitcoin-af998da072f0-riscv64-linux-gnu.tar.gz

ff0eb7032334e83ee49ac71e3d6e8e5254312bf51a978519186568b028fb3397  guix-build-af998da072f0/output/x86_64-apple-darwin/SHA256SUMS.part
864df3529d2c58d27855ed956945cdd5ba95d4ebfbc8cfcc8dc36b42fa35153f  guix-build-af998da072f0/output/x86_64-apple-darwin/bitcoin-af998da072f0-x86_64-apple-darwin-unsigned.tar.gz
065c8524a11be7d39aa6873afedc204ed9aefd041010cc5aaf38bfdb7e8d5ae7  guix-build-af998da072f0/output/x86_64-apple-darwin/bitcoin-af998da072f0-x86_64-apple-darwin-unsigned.zip
a9e53a906c8aa0760fc819b17e504d7d96fac117de57ab1e1d2f8582b3e64b99  guix-build-af998da072f0/output/x86_64-apple-darwin/bitcoin-af998da072f0-x86_64-apple-darwin.tar.gz

0eb02af52fe7dce373e2f797e5f12f27daeef2a0881d37507fe9fcac1fa47edc  guix-build-af998da072f0/output/x86_64-linux-gnu/SHA256SUMS.part
4b2d7d7ba4759a88898791064eb50aeccdd1b53ad5bba82f60e6207961ac241e  guix-build-af998da072f0/output/x86_64-linux-gnu/bitcoin-af998da072f0-x86_64-linux-gnu-debug.tar.gz
7e77275871af4845820e6681671d4e1be7d3b26669bb394fb0fa7cb3ac19f9a5  guix-build-af998da072f0/output/x86_64-linux-gnu/bitcoin-af998da072f0-x86_64-linux-gnu.tar.gz

7674627f30c9660d97c8d0b21fa7b5fe59cd7282af5eb8cb3d5d928bca85b566  guix-build-af998da072f0/output/x86_64-w64-mingw32/SHA256SUMS.part
85e363c3b24851cc30cb912039492adc3d9d85b2f545d936b54212670af325fc  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64-debug.zip
d57571dd880e0f1dcd24f0f55560bdd0559f55a28aea013d0da41f551d34b152  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64-setup-unsigned.exe
dc534082714bb978499c2aa44207158a71a29d9bd7cab522cde3fd3629244e66  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64-unsigned.tar.gz
25b474a9c1debd04dd4055afa070952db3e95b303c3f80cfe3313884861a3471  guix-build-af998da072f0/output/x86_64-w64-mingw32/bitcoin-af998da072f0-win64.zip

```

</details>

**Comment by m3dwards** [comment]
ACK https://github.com/hebasto/bitcoin/commit/af998da072f09e47e5fda0489b62c8832ab22e7e

Got zero differences between the output of this process and hebasto/240416-linear.

Running guix and will update with hashes.

**Comment by m3dwards** [comment]
My Guix builds do not match however.

```shell
46dd97cf462d4debd29d895de1586e6f1874688c331fa48b099bf09271770a5b  bitcoin-984c548086d2-aarch64-linux-gnu-debug.tar.gz
65d9f061a41adb39e8115be2faab7a616d2ee44266ecdf8965837a0ff96e6ede  bitcoin-984c548086d2-aarch64-linux-gnu.tar.gz
74de989391f1c38eb710c0fc2b12a84e8fd621e7526acd423c1405a33fab3f7d  bitcoin-984c548086d2-arm-linux-gnueabihf-debug.tar.gz
6021423ae5bda75438e1bb692670baa8f368c9ae680ea0b5f2ef12dd0e0c7c38  bitcoin-984c548086d2-arm-linux-gnueabihf.tar.gz
15569069d5e6019dfa43b82403322673bdb97abc85a342aa83a7f843a2f1de6a  bitcoin-984c548086d2-arm64-apple-darwin-unsigned.tar.gz
9583a1731629ea1504d37320ff3fdae39a819d63c2ab9670208777c32444eede  bitcoin-984c548086d2-arm64-apple-darwin-unsigned.zip
d8e0b331f18908492ec3c8c45308deafa786f31f76991bd0452b3402ed7cda98  bitcoin-984c548086d2-arm64-apple-darwin.tar.gz
d095cd5d6a17e5253deb5a3e0f2a29368879eb593faf46cc522c348275ab3336  bitcoin-984c548086d2.tar.gz
718d5d1e9bce5c3db44b1ea2ed9dfe2856845c22872461b32efdf0ab61acd4c4  bitcoin-984c548086d2-powerpc64-linux-gnu-debug.tar.gz
e3b7c03a866088f2af7d986be3f079b724991eead68e3f62c7fed3bf1849a896  bitcoin-984c548086d2-powerpc64-linux-gnu.tar.gz
bd7197a6b1d3e4008fc5fa1542cc802a89304861eb09786768355ac15346c564  bitcoin-984c548086d2-riscv64-linux-gnu-debug.tar.gz
0710c40838e824dfedee4fbf9245b3d9fa15f2bdca2cf9dd08416357d019fffb  bitcoin-984c548086d2-riscv64-linux-gnu.tar.gz
1823cdb3c67ab3d2ef5379bf6e0df55734dc7dd0a68d3192bafa7a9cec778174  bitcoin-984c548086d2-x86_64-apple-darwin-unsigned.tar.gz
1a29814243d019f96e02c8c19fab063f4237f18272d9e67fdf4c4abb0d407525  bitcoin-984c548086d2-x86_64-apple-darwin-unsigned.zip
2eab8a1771ea61a818358fb736e78dbbb9a1a7e75d44e9c3d58bb2081cd3351d  bitcoin-984c548086d2-x86_64-apple-darwin.tar.gz
9bb78afd34517972fb9c258ed291704ae129508cde0cffd38f62a7b1dae25ee1  bitcoin-984c548086d2-x86_64-linux-gnu-debug.tar.gz
a5f5fd0f3ced0d387b9c950b6fa40c21dea5da9596a53a98f98d9cce2a19416e  bitcoin-984c548086d2-x86_64-linux-gnu.tar.gz
1e6f043b8fbfc1f3022ee3cac05328d1dbdaabd023bb54bff2cb7218606e423f  bitcoin-984c548086d2-win64-debug.zip
e623eb4427926b43a32842b1f34f5a2ed9803794f44bc51fa02ae7d760655143  bitcoin-984c548086d2-win64-setup-unsigned.exe
90e570cfa6498474d8f14a238470701d7b405348aa29c6d9ebb3aa07d2f20de8  bitcoin-984c548086d2-win64-unsigned.tar.gz
cb8abbe41247e028a97e9beb9715f1d7bbc845e754d6ba0b989f0543380edf7f  bitcoin-984c548086d2-win64.zip
```

**Comment by hebasto** [comment]
> My Guix builds do not match however.
> 
> 
> 
> ```shell
> 
> 46dd97cf462d4debd29d895de1586e6f1874688c331fa48b099bf09271770a5b  bitcoin-984c548086d2-aarch64-linux-gnu-debug.tar.gz
> 
> 65d9f061a41adb39e8115be2faab7a616d2ee44266ecdf8965837a0ff96e6ede  bitcoin-984c548086d2-aarch64-linux-gnu.tar.gz
> 
> 74de989391f1c38eb710c0fc2b12a84e8fd621e7526acd423c1405a33fab3f7d  bitcoin-984c548086d2-arm-linux-gnueabihf-debug.tar.gz
> 
> 6021423ae5bda75438e1bb692670baa8f368c9ae680ea0b5f2ef12dd0e0c7c38  bitcoin-984c548086d2-arm-linux-gnueabihf.tar.gz
> 
> 15569069d5e6019dfa43b82403322673bdb97abc85a342aa83a7f843a2f1de6a  bitcoin-984c548086d2-arm64-apple-darwin-unsigned.tar.gz
> 
> 9583a1731629ea1504d37320ff3fdae39a819d63c2ab9670208777c32444eede  bitcoin-984c548086d2-arm64-apple-darwin-unsigned.zip
> 
> d8e0b331f18908492ec3c8c45308deafa786f31f76991bd0452b3402ed7cda98  bitcoin-984c548086d2-arm64-apple-darwin.tar.gz
> 
> d095cd5d6a17e5253deb5a3e0f2a29368879eb593faf46cc522c348275ab3336  bitcoin-984c548086d2.tar.gz
> 
> 718d5d1e9bce5c3db44b1ea2ed9dfe2856845c22872461b32efdf0ab61acd4c4  bitcoin-984c548086d2-powerpc64-linux-gnu-debug.tar.gz
> 
> e3b7c03a866088f2af7d986be3f079b724991eead68e3f62c7fed3bf1849a896  bitcoin-984c548086d2-powerpc64-linux-gnu.tar.gz
> 
> bd7197a6b1d3e4008fc5fa1542cc802a89304861eb09786768355ac15346c564  bitcoin-984c548086d2-riscv64-linux-gnu-debug.tar.gz
> 
> 0710c40838e824dfedee4fbf9245b3d9fa15f2bdca2cf9dd08416357d019fffb  bitcoin-984c548086d2-riscv64-linux-gnu.tar.gz
> 
> 1823cdb3c67ab3d2ef5379bf6e0df55734dc7dd0a68d3192bafa7a9cec778174  bitcoin-984c548086d2-x86_64-apple-darwin-unsigned.tar.gz
> 
> 1a29814243d019f96e02c8c19fab063f4237f18272d9e67fdf4c4abb0d407525  bitcoin-984c548086d2-x86_64-apple-darwin-unsigned.zip
> 
> 2eab8a1771ea61a818358fb736e78dbbb9a1a7e75d44e9c3d58bb2081cd3351d  bitcoin-984c548086d2-x86_64-apple-darwin.tar.gz
> 
> 9bb78afd34517972fb9c258ed291704ae129508cde0cffd38f62a7b1dae25ee1  bitcoin-984c548086d2-x86_64-linux-gnu-debug.tar.gz
> 
> a5f5fd0f3ced0d387b9c950b6fa40c21dea5da9596a53a98f98d9cce2a19416e  bitcoin-984c548086d2-x86_64-linux-gnu.tar.gz
> 
> 1e6f043b8fbfc1f3022ee3cac05328d1dbdaabd023bb54bff2cb7218606e423f  bitcoin-984c548086d2-win64-debug.zip
> 
> e623eb4427926b43a32842b1f34f5a2ed9803794f44bc51fa02ae7d760655143  bitcoin-984c548086d2-win64-setup-unsigned.exe
> 
> 90e570cfa6498474d8f14a238470701d7b405348aa29c6d9ebb3aa07d2f20de8  bitcoin-984c548086d2-win64-unsigned.tar.gz
> 
> cb8abbe41247e028a97e9beb9715f1d7bbc845e754d6ba0b989f0543380edf7f  bitcoin-984c548086d2-win64.zip
> 
> ```
> 
> 

Your filenames show that you built for the 984c548086d2 commit rather than af998da072f0.

**Comment by hebasto** [comment]
> > Your filenames show that you built for the https://github.com/hebasto/bitcoin/commit/984c548086d2f2f150713b0307d922420be2fd7c commit rather than https://github.com/hebasto/bitcoin/commit/af998da072f09e47e5fda0489b62c8832ab22e7e.
> 
> 
> 
> I have no codefile changes between my branch and that though so I naively expected the guix build to come out the same
> 
> 
> 
> ```shell
> 
> DebainBuild ➜  bitcoin git:(0593892153) git --no-pager diff af998da072f09e47e5fda0489b62c8832ab22e7e
> 
> DebainBuild ➜  bitcoin git:(0593892153)
> 
> ```

The top commit hash becomes a part of the source via the `obj/build.h` header.

**Comment by hebasto** [comment]
@pablomartin4btc @m3dwards

Thank you for your reviews!

---

This branch has been force pushed into the https://github.com/hebasto/bitcoin/tree/cmake-staging.

Closing.

**Comment by hebasto** [comment]
> The build system related changes from the following PRs:
> 
>    * [Replace Boost.Process with cpp-subprocess bitcoin/bitcoin#28981](https://github.com/bitcoin/bitcoin/pull/28981)
> 
>    * [refactor: Remove gmtime* bitcoin/bitcoin#29081](https://github.com/bitcoin/bitcoin/pull/29081)
> 
>    * [Drop Windows Socket dependency for `randomenv.cpp` bitcoin/bitcoin#29786](https://github.com/bitcoin/bitcoin/pull/29786) -- done in https://github.com/hebasto/bitcoin/pull/149.
> 
>    * [crypto: chacha20: always use our fallback timingsafe_bcmp rather than libc's bitcoin/bitcoin#29815](https://github.com/bitcoin/bitcoin/pull/29815)
> 
>    * [minisketch: update subtree to 3472e2f5ec75ace39ce9243af6b3fee233a67492 bitcoin/bitcoin#29823](https://github.com/bitcoin/bitcoin/pull/29823)
> 
> 
> are to be backported in dedicated PRs shortly after approving this one.

**Comment by m3dwards** [comment]
Post merge Guix builds match

```shell
ed28ca2a53077f6220ef0923525598a84db4c06287ce9d3f8f936dedc4a1aefe  bitcoin-af998da072f0-aarch64-linux-gnu-debug.tar.gz
e1f6fef3580f6abb6b4dc7ce75f55f0411c17cf67f5a9f1346bf5322a063d0b9  bitcoin-af998da072f0-aarch64-linux-gnu.tar.gz
130125f4c8feeef68701f7dc1a64280d5faa8eae34ff8a7f5a6b68de731a38a0  bitcoin-af998da072f0-arm-linux-gnueabihf-debug.tar.gz
6cbeea795f7103281b5e8498074522efb788b48c220710b223531a26a213bc42  bitcoin-af998da072f0-arm-linux-gnueabihf.tar.gz
058cf37206f77a4c4a41087780c035fa239b82cf8df4260060ebc092bc2a81e5  bitcoin-af998da072f0-arm64-apple-darwin-unsigned.tar.gz
e4d346f780687658fa05fc445dd42fa43ad4893012c64972e37471a05646fc1e  bitcoin-af998da072f0-arm64-apple-darwin-unsigned.zip
1f242a96230f0700b8ea515f3994ce88df6152d6787acf1dd59c8500bb7048fc  bitcoin-af998da072f0-arm64-apple-darwin.tar.gz
c743c73bdc6cc87c28e4648e3563baed85d9decc324476ba542b8e25b84955ff  bitcoin-af998da072f0.tar.gz
19ac54f0d59fefbf58c879edf4e07aa5259605ab6b26778084d145320374508d  bitcoin-af998da072f0-powerpc64-linux-gnu-debug.tar.gz
d316720fc8a2680a7d068087e6dbf41c7f5c0c82e2d09b550512bf292b883b96  bitcoin-af998da072f0-powerpc64-linux-gnu.tar.gz
efb86cb221252b88f2e561f575ac51a9c905dbf8bdde72c6d531062dda5178be  bitcoin-af998da072f0-riscv64-linux-gnu-debug.tar.gz
3a785b732cb3bd060fe5fd976312f43590c150ec5975c6c0f081a891664335c3  bitcoin-af998da072f0-riscv64-linux-gnu.tar.gz
864df3529d2c58d27855ed956945cdd5ba95d4ebfbc8cfcc8dc36b42fa35153f  bitcoin-af998da072f0-x86_64-apple-darwin-unsigned.tar.gz
065c8524a11be7d39aa6873afedc204ed9aefd041010cc5aaf38bfdb7e8d5ae7  bitcoin-af998da072f0-x86_64-apple-darwin-unsigned.zip
a9e53a906c8aa0760fc819b17e504d7d96fac117de57ab1e1d2f8582b3e64b99  bitcoin-af998da072f0-x86_64-apple-darwin.tar.gz
4b2d7d7ba4759a88898791064eb50aeccdd1b53ad5bba82f60e6207961ac241e  bitcoin-af998da072f0-x86_64-linux-gnu-debug.tar.gz
7e77275871af4845820e6681671d4e1be7d3b26669bb394fb0fa7cb3ac19f9a5  bitcoin-af998da072f0-x86_64-linux-gnu.tar.gz
85e363c3b24851cc30cb912039492adc3d9d85b2f545d936b54212670af325fc  bitcoin-af998da072f0-win64-debug.zip
d57571dd880e0f1dcd24f0f55560bdd0559f55a28aea013d0da41f551d34b152  bitcoin-af998da072f0-win64-setup-unsigned.exe
dc534082714bb978499c2aa44207158a71a29d9bd7cab522cde3fd3629244e66  bitcoin-af998da072f0-win64-unsigned.tar.gz
25b474a9c1debd04dd4055afa070952db3e95b303c3f80cfe3313884861a3471  bitcoin-af998da072f0-win64.zip
```

**Comment by hebasto** [comment]
> Post merge ...

Rather "post force push" :)

**Pull request closed without merging**
