### PR TITLE
cmake: Fix `toolchain.cmake` for *BSD systems

### PR DESCRIPTION
**Pull request by hebasto**
For *BSD systems, the `qt` and `qrencode` packages are not built, even without the `NO_QT` or `NO_QR` variables defined, because these package are not available for the host systems: https://github.com/hebasto/bitcoin/blob/19d4d920d97aa7fc4675eb4ac4ecf744e9ec8613/depends/packages/packages.mk#L7-L13

We already handle the exact logic for the `systemtap` (USDT) package. Therefore, it is reasonable to use this working logic uniformly for all cases.

Additionally, this PR correctly handles cases when a `*_packages_`  variable contains only spaces rather than being empty.

---

How to test this PR on a *BSD system:
1. Build depends following the build guides (`depends/README.md`, `doc/build-*bsd.md`)
2. Configure the main build system using the generated toolchain file:
```
cmake -B build --toolchain depends/<your-platform>/toolchain.cmake
```
It fails.

With this PR it configures successfully.

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @theStack :)

**Review by vasild — APPROVED** [review]
ACK 20ef783ddd4d37f8706bd1d1eca6fe37f0d0a0ad

> ... because these package are not available for the host systems ...

Why? FreeBSD has packages for qt and qrencode.

**Comment by hebasto** [comment]
@vasild 

Test instructions have been added to the PR description per your request.

**Comment by vasild** [comment]
I tested this on FreeBSD: on `cmake-staging` it fails with:

```
-- Checking for module 'libqrencode'
--   Package 'libqrencode' not found
CMake Error at /usr/local/share/cmake/Modules/FindPkgConfig.cmake:634 (message):
  The following required packages were not found:

   - libqrencode
```

and succeeds with the changes from this branch.

Unrelated to this PR: `depends/README.md` mentions to run `make` followed by `cmake -B build ...` but those have to be run from different directories - `make` has to be in the `depends/` subdirectory. On FreeBSD `make` spits a ton of syntax errors because `depends/Makefile` is gnu-make specific, so I used `gmake -C depends` from the top source directory.

**Pull request merged**
