### PR TITLE
cmake, ci: Bump clang version to 15

### PR DESCRIPTION
**Pull request by hebasto**
See https://github.com/bitcoin/bitcoin/pull/29165.

### CODE REVIEW

**Comment by hebasto** [comment]
> Is this being moved away from our minimum on purpose?

These CI tasks are to test CMake-specific points of the build system rather than compiler support in general. And `.github/workflows/cmake.yml` won't go to the master branch.

> Otherwise I don't see why this is needed

To keep CI config simpler.

> how [bitcoin#29859](https://github.com/bitcoin/bitcoin/pull/29859) is related to unreachable code warnings.

https://github.com/bitcoin/bitcoin/pull/29859 is related to compiling with clang-15.

**Comment by vasild** [comment]
FWIW on latest `master` @ 2a07c4662d7266158d47f79fa2433ab22e22c907 with clang 19 I see:

```
clang++-devel -std=c++20 -DHAVE_CONFIG_H -I. -I../src/config  -DDEBUG -DDEBUG_LOCKORDER -DDEBUG_LOCKCONTENTION -DRPC_DOC_CHECK -DABORT_ON_FAILED_ASSUME  -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION -I. -I./minisketch/include -I./secp256k1/include -I./univalue/include  -isystem /usr/local/include -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -isystem /usr/local/include  -I/usr/local/include -g -O2 -O0 -g3 -ftrapv -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wloop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wimplicit-fallthrough -Wunreachable-code -Wdocumentation -Wno-unused-parameter -Wno-self-assign -Werror   -fPIE  -MT test/test_bitcoin-util_threadnames_tests.o -MD -MP -MF test/.deps/test_bitcoin-util_threadnames_tests.Tpo -c -o test/test_bitcoin-util_threadnames_tests.o `test -f 'test/util_threadnames_tests.cpp' || echo './'`test/util_threadnames_tests.cpp

test/util_threadnames_tests.cpp:62:35: error: code will never be executed [-Werror,-Wunreachable-code]
   62 |     std::set<std::string> names = RenameEnMasse(100);
      |                                   ^~~~~~~~~~~~~

```

**Comment by fanquake** [comment]
I'm assuming that's on FreeBSD? If so, I assume it's because we currently outright disable thread local.

**Comment by vasild** [comment]
@fanquake, yes to both.

**Comment by hebasto** [comment]
Rebased to resolve conflicts.

**Comment by hebasto** [comment]
I've updated PR title and description in the light of the merged https://github.com/bitcoin/bitcoin/pull/29165.

**Comment by hebasto** [comment]
cc @m3dwards @vasild @pablomartin4btc

**Comment by m3dwards** [comment]
utACK https://github.com/hebasto/bitcoin/pull/159/commits/8fd40d42475cccb7323e488a572ddd5f8d42b2f1

**Pull request merged**
