### PR TITLE
cmake: Drop extraneous `-fvisibility-inlines-hidden`

### PR DESCRIPTION
**Pull request by hebasto**
This PR mirrors the master branch behavior and addresses https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1703899727.

### CODE REVIEW

**Comment by m3dwards** [comment]
ACK 4dd3928d3ffb9eceabc04ce960436df642fee202

Straightforward enough. Test on Aarch Mac.

**Comment by fanquake** [comment]
How did this end up getting added in the first place?

**Comment by hebasto** [comment]
> How did this end up getting added in the first place?

It was added in https://github.com/hebasto/bitcoin/pull/32.

**Comment by fanquake** [comment]
> It was added in https://github.com/hebasto/bitcoin/pull/32.

Right, my question was why? It's odd that if it was done on purpose, it'd just be removed with 0 explanation, because if there was a reason, then a PR to master with the same justification would be made. Otherwise, I was wondering why it was added.

**Comment by hebasto** [comment]
> > It was added in #32.
> 
> Right, my question was why?

I don't remember almost a year old staff.

> It's odd that if it was done on purpose, it'd just be removed with 0 explanation, because if there was a reason, then a PR to master with the same justification would be made. Otherwise, I was wondering why it was added.

Whatever the initial purpose was, "to mirror the master branch behavior" sounds like an explanation for removal, no?

**Comment by theuni** [comment]
It was probably added because the two visibility options get set together: both on or both off. @hebasto probably just assumed that logic at the time.

Might be worth a PR to add it to master rather than removing it here.

**Pull request merged**
