### PR TITLE
CMakeLists.txt: USDT package error

### PR DESCRIPTION
**Pull request by RandyMcMillan**
find_package(USDT MODULE REQUIRED) if UNIX AND NOT APPLE

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
There may be a better way but this works on macOS.

**Comment by RandyMcMillan** [comment]
Note: even with the option OFF on macOS - it hash this error.

Screenshot 2024-05-29 at 7 22 14 PM

**Comment by RandyMcMillan** [comment]
Xcode:


```cmake . -B xcode -G Xcode```

```cd Xcode/```

```xcodebuild```

Tested the resulting Xcode project for thoroughness:

Screenshot 2024-05-29 at 7 52 06 PM

Screenshot 2024-05-29 at 7 57 18 PM


Darwin DeepSpaceMBPro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

**Comment by hebasto** [comment]
cc @m3dwards

**Comment by m3dwards** [comment]
I could not recreate this:

```shell
mkdir build
cmake -B build -G Xcode
cd build
xcodebuild

...

Build all projects

note: Run script build phase 'Generate CMakeFiles/ZERO_CHECK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ZERO_CHECK' from project 'BitcoinCore')
** BUILD SUCCEEDED **
```

Tools installed:

Arm M1 Mac running MacOS 14.0 (Sonoma)
Xcode 15.4
Apple clang version 15.0.0 (clang-1500.0.40.1)
cmake version 3.29.3

**Comment by RandyMcMillan** [comment]
thanks for looking...

I am guessing - even though the repo was clean...

The shell env may have been stale - based on a previous
state of the repo and CMake config?

Or a residual config/variable from
another CMake project?

Some additional guards may still be useful.

**Pull request closed without merging**
