### PR TITLE
more macOS testing feedback

### PR DESCRIPTION
**Pull request by RandyMcMillan**
brew install libnatpmp qrencode cppzmq

https://github.com/hebasto/bitcoin/assets/152159/2a609840-40f5-4e78-94ff-6563847edc51

cmake version 3.29.2
Darwin DeepSpaceMBPro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

changes below were used to generate ```build``` on macOS Ventura 13.5 (22G74)

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
close PR after reading

**Comment by hebasto** [comment]
@RandyMcMillan 

Could you please clarify what the problem is?

**Comment by RandyMcMillan** [comment]
in the ccmake console - there were extraneous .....

probably doesnt matter...

**Comment by RandyMcMillan** [comment]
BUILD_DAEMON has port...

**Comment by RandyMcMillan** [comment]
feel free to close - just posting things i noticed.

**Comment by hebasto** [comment]
I can't reproduce it.

On my macOS 14.5 with Homebrew's CMake 3.29.6:

image

**Comment by hebasto** [comment]
It is essential to tell whether the issue is specific to our project or is related to `ccache`.

**Pull request closed without merging**
